= Step 05 : Adding an In Memory Database
:source-highlighter: prettify
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Summary

Now that we have stubbed out the Register User methods it is time to do some real work.  In this step we will create a database for our application and persist a User

== KeyTerms in this Step

* Flyway database migration tool: https://flywaydb.org
* HyperSQL http://hsqldb.org/

* io.vertx.ext.jdbc.JDBCClient

=== Flyway

Flyway is a databse migration tool.  Programmatic database migrations were introduced by Ruby on Rails. Flyway is a Java application and fits nicely into the Java build ecosystem, but it will feel familiar to anyone who has used Rails before

Flyway has a command line tool, a Java API that can be executed from your application, and a Maven plugin.  We will use the maven plugin and the Java API in our Unit Tests.  There are only a couple of commands that you have to know to use Flyway

You can run the Flyway Maven commands like this:

[code,shell]
....

mvn flyway:migrate

....

The Java API is similarly straightforward:

[code,java]
....

    Flyway flyway = Flyway.configure().dataSource(DB_URL_TEST, DB_USER_TEST, null).load();
    flyway.migrate();

....

NOTE: If for some reason something goes wrong with a Flyway migration you need to run "mvn flyway:repair" before rerunning the migration.  You can also safely delete the enire "db" folder, which will be in the root of your project, and re-run "mvn flyway:migrate"

==== Properties, Dependencies, and Plugin

The Flyway properties on line 18 of the pom.xml, the dependency on line 92, and the plugin on line 115.

===== Properties

[code,xml]
....

    <!-- Flyway Database Migrations -->
    <flyway.url>jdbc:hsqldb:file:db/conduit</flyway.url>     <1>
    <flyway.driver>org.hsqldb.jdbcDriver</flyway.driver>     <2>
    <flyway.locations>filesystem:src/main/resources/db/migration</flyway.locations>     <3>

....

<1> The filesystem location of our HyperSQL database
<2> The JDBC driver
<3> The location where we will keep our migration scripts.  This is the default location for the Java API

===== Dependency

The flyway-core dependency is required to use Flyway in Java classes.  We will be using it to create tables and populate data in memory for use in our Unit Tests

[code,xml]
....

<dependency>
  <groupId>org.flywaydb</groupId>
  <artifactId>flyway-core</artifactId>
  <version>5.2.0</version>
</dependency>

....

===== Plugin

The Maven plugin makes it easy to create tables and populate data before running the application

[code,xml]
....

<plugin>
  <groupId>org.flywaydb</groupId>
  <artifactId>flyway-maven-plugin</artifactId>
  <version>5.1.4</version>
</plugin>
        
....

=== HyperSQL (HSQLDB)

HyperSQL, http://hsqldb.org, is a small relational database that can be store data in-memory or on the file system.  We will use both methods in ths project.

HSQLDB isn't recommended for production systems, but it is an excellent choice for development.

The database dependencies can be found in the pom.xml on line 64

[source,xml]
....
    <!-- Database Dependencies -->
    <dependency>
      <groupId>io.vertx</groupId> 
      <artifactId>vertx-jdbc-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
    </dependency>
....

== Fail a Test

First things first we need to fail a test

=== Database Configuration

The Flyway section of this document mentioned that we will be using HSQLDB's File System and In-Memory modes.  HSQLDB's in-memory mode gives us the ability to create the database in memory before every test

We will share the database properties across multiple objects so we should keep those in a single location.  Create a new class, "DatabaseProps," in the "io.vertx.conduit.persistence" package:

src/main/java/io/vertx/conduit/persistence/DatabaseProps.java
[code,java]
....

package io.vertx.conduit.persistence;

public class DatabaseProps {

  protected static final String DB_DRIVER_KEY = "driver_class";
  protected static final String DB_POOL_SIZE_KEY = "max_pool_size";
  protected static final String DB_URL_KEY = "url";
  protected static final String DB_USER_KEY = "user";

  protected static final String DB_DRIVER_DEFAULT = "org.hsqldb.jdbcDriver";
  protected static final Integer DB_POOL_SIZE_DEFAULT = 30;
  protected static final String DB_URL_DEFAULT = "jdbc:hsqldb:file:db/conduit;shutdown=true";
  protected static final String DB_USER_DEFAULT = "sa";

}

....

Let's do the same for test properties and create a class, "TestDatabaseProps," in test directory:

src/test/java/io/vertx/conduit/persistence/TestDatabaseProps.java
[code,java]
....

package io.vertx.conduit.persistence;

public class TestDatabaseProps {

  protected static final String DB_URL_TEST = "jdbc:hsqldb:mem:testdb;db_close_delay=-1";
  protected static final String DB_DRIVER_TEST = "org.hsqldb.jdbcDriver";
  protected static final String DB_USER_TEST = "sa";
  protected static final Integer DB_POOL_SIZE_TEST = 30;

}

....

=== And Queries

We will externalize the queries as well.  Create a file SQLQueries in the persistence package:

src/main/java/io/vertx/conduit/persistence/SQLQueries.java
[code,java]
....

package io.vertx.conduit.persistence;

public class SQLQueries {

  public static final String SQL_REGISTER_USER = "insert into USER (\"username\",\"email\",\"bio\",\"password\") values (?, ?, ?, ?);";
  public static final String SQL_SELECT_USER_BY_EMAIL = "select * from USER where \"email\" = ?";

}

....

=== Update the Unit Test

Now we can update PersistenceVerticleTest:

src/main/test/io/vertx/conduit/persistence/PersistenceVerticleTest
[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static io.vertx.conduit.persistence.DatabaseProps.*;          <1>
import static io.vertx.conduit.persistence.TestDatabaseProps.*;         <2>

@DisplayName("Persistence Event Bus Tests")
@ExtendWith(VertxExtension.class)
public class PersistenceVerticleTest {

  private JDBCClient jdbcClient;         <3>

  @BeforeEach
  void setUp(Vertx vertx, VertxTestContext testContext) {          <4>

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()         <5>
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST));

    Flyway flyway = Flyway.configure().dataSource(DB_URL_TEST, DB_USER_TEST, null).load();         <6>
    flyway.migrate();         <7>

    testContext.completeNow();         <8>
  }

  @Test
  @DisplayName("Register User Test") 
  @Timeout(2000)
  void testServerRegisterUserOverEventBus(Vertx vertx, VertxTestContext testContext) {

    Checkpoint deploymentCheckpoint = testContext.checkpoint();
    Checkpoint replyCheckpoint = testContext.checkpoint();

    User user = new User("user1@user.com", null, "user1", "user1's bio", null);

    JsonObject message = new JsonObject()
      .put(PERSISTENCE_ACTION, PERSISTENCE_ACTION_REGISTER)         
      .put("user", Json.encode(user));

    vertx.deployVerticle(new PersistenceVerticle(), testContext.succeeding(id -> {         
      deploymentCheckpoint.flag();          
      vertx.eventBus().send(PERSISTENCE_ADDRESS, message, testContext.succeeding(ar -> {          
        testContext.verify(() -> {          
          assertEquals(PERSISTENCE_OUTCOME_SUCCESS, ((JsonObject) ar.body()).getString("outcome"));
          replyCheckpoint.flag();        
          testContext.completeNow();        
        });
      }));
    }));
  }
}

....

<1>  Import the DatabaseProps constants
<2>  Import the TestDatabaseProps constants
<3>  We will need a local JDBCClient to query the database and verify the insert worked
<4>  We have added a @BeforeEach method that will run before each test and run the database migrations  
<5>  Instantiate the JDBCClient with the constants in TestDatabaseProps
<6>  Instantiate our Flyway object with the test properties
<7>  Perform the database migration creating our user table (we will create the migration in the next step
<8>  Be sure to let JUnit and the VertxExtension that the @Before method is finished!

IMPORTANT: The Unit Test won't exit without the testContext.completeNow() call.  Keep this in mind if you ever find yourself waiting for your Unit Test to complete

=== Create the Migration

Create a folder src/main/resources/db/migration.  This is the default Flyway location, and there is no compelling reason to change it

Create a new file named "V1_\_create-user-table.sql," in this directory.  Be sure to have 2 underscores between the V1 and the name of the migration

We can craft a "create table" statement using the values from the json outlined in the API.  The Registration endpoint expects a Post request at "/api/users" with the following body:

[code,json]
....

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

....

Our API defines the following response:

[code,json]
....

{
  "user": {
    "email": "jake@jake.jake",
    "token": "jwt.token.here",
    "username": "jake",
    "bio": "I work at statefarm",
    "image": null
  }
}

....

The combined values produce the following table which becomes our V1 migration:

src/main/java/resources/db/migration/V1_\_create-user-table.sql

[code,sql]
....

create table if not exists USER ("id" INT IDENTITY PRIMARY KEY ,
  "username" VARCHAR(255) NOT NULL ,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "bio" VARCHAR(255) ,
  "image" VARCHAR(255) ,
  "password" VARCHAR(255) NOT NULL);

....

Run the test to verify that the migration works:

[code,shell]
....

mvn clean test -Dtest=PersistenceVerticleTest          <1>

....

<1> The flag "-Dtest=PersistenceVerticleTest" limits execution to only PersistenceVerticleTest

The test will fail, but check the logs for a message about the migration:

[code,shell]
....

INFO: Migrating schema "PUBLIC" to version 1 - create-user-table
Oct 13, 2018 6:44:50 AM org.flywaydb.core.internal.command.DbMigrate logSummary
INFO: Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.028s)          <1>
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.674 s <<< FAILURE! - in io.vertx.conduit.persistence.NewPersistenceVerticleTest
[ERROR] testServerRegisterUserOverEventBus{Vertx, VertxTestContext}  Time elapsed: 0.672 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at io.vertx.conduit.persistence.NewPersistenceVerticleTest.testServerRegisterUserOverEventBus(NewPersistenceVerticleTest.java:46)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   NewPersistenceVerticleTest.testServerRegisterUserOverEventBus:46 expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

....

<1>  The log, "INFO: Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.028s)" is what we are looking for

=== Verify the Insert

There is one last step: we need to verify that our user was saved to the database.  Add the following code to PersistenceVerticleTest:

src/main/test/io/vertx/conduit/persistence/PersistenceVerticleTest
[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.conduit.model.User;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.json.Json;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.SQLConnection;
import io.vertx.junit5.Checkpoint;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static io.vertx.conduit.SQLQueries.SQL_SELECT_USER_BY_EMAIL;
import static io.vertx.conduit.persistence.DatabaseProps.*;
import static io.vertx.conduit.persistence.PersistenceVerticle.*;
import static io.vertx.conduit.persistence.TestDatabaseProps.*;

@DisplayName("Persistence Event Bus Tests")
@ExtendWith(VertxExtension.class)
public class PersistenceVerticleTest {

  private JDBCClient jdbcClient;


  @BeforeEach
  void setUp(Vertx vertx, VertxTestContext testContext) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST));

    Flyway flyway = Flyway.configure().dataSource(DB_URL_TEST, DB_USER_TEST, null).load();
    // Run the migration
    flyway.migrate();

    testContext.completeNow();
  }

  @Test
  @DisplayName("Register User Test")
  @Timeout(10000)
  void testServerRegisterUserOverEventBus(Vertx vertx, VertxTestContext testContext) {

    Checkpoint deploymentCheckpoint = testContext.checkpoint();
    Checkpoint replyCheckpoint = testContext.checkpoint();

    User user = new User("user1@user.com", null, "user1", "user1's bio", null, "password");

    JsonObject message = new JsonObject()
      .put(PERSISTENCE_ACTION, PERSISTENCE_ACTION_REGISTER)
      .put("user", Json.encode(user));

    JsonObject eventBusDeploymentConfig = new JsonObject()          <1>
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST);


    vertx.deployVerticle(new PersistenceVerticle(), new DeploymentOptions().setConfig          <2>(eventBusDeploymentConfig),testContext.succeeding(id -> {
      deploymentCheckpoint.flag();
      vertx.eventBus().send(PERSISTENCE_ADDRESS, message, testContext.succeeding(ar -> {
        testContext.verify(() -> {
    
          // query database to verify insert
          jdbcClient.getConnection(conn ->{          <3>
            if (conn.failed()) {
              Assertions.assertTrue(conn.succeeded());          <4>
              testContext.completeNow();          <5>
            }
            final SQLConnection connection = conn.result();          <6>

            connection.queryWithParams(SQL_SELECT_USER_BY_EMAIL,          <7> 
               new JsonArray().add(user.getEmail()),          <8> 
               rs -> {
                if (rs.failed()) {
                  Assertions.assertTrue(rs.succeeded());          <9>
                  testContext.completeNow();          <10>
                }
                Assertions.assertEquals(1, rs.result().getNumRows());          <11>
                System.out.println(rs.result().getResults().get(0).encode());
              });
            });

          Assertions.assertEquals(PERSISTENCE_OUTCOME_SUCCESS, ((JsonObject) ar.body()).getString("outcome"));
          replyCheckpoint.flag();
          testContext.completeNow();
        });
      }));
    }));
  }

}

....

<1>  Create a JsonObject to pass the configuration for the EventBus
<2>  Add the configuration as the second parameter when deploying the PersistenceVerticle
<3>  Use the jdbcClient to get a database connection
<4>  If we can't get a connection we can fail the test
<5>  Be sure to let the VertxExtension know we are done!
<6>  The SQLConnection is the result of getConnection
<7>  Use SQLConnection's queryWithParams method to retrieve our new User by email.  
<8>  The queryWithParams method gets the parameters to use in the query from a JsonArray.  Add the User's email to a new JsonArray
<9>  If there are no results we can fail the test
<10>  Be sure to let the VertxExtension know we are done!
<11>  Verify that we have a single result


We haven't created the constants for the keys.  We will add those in the next step as publicly available constants in the PersistenceVerticle class
<4>  Pass a DeploymentOptions object with our configuration as the second argument to deployVerticle().  The configuration will automatically be read by the Verticle if it is present

=== Modify Our Class Under Test

We need to add the JDBC constants to PersistenceVerticle:

src/main/java/io/vertx/conduit/persistence/PersistenceVerticle.java
[code,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";          <1>
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";

  public static final String DB_DRIVER_KEY = "driver_class";          <2>
  public static final String DB_POOL_SIZE_KEY = "max_pool_size";
  public static final String DB_URL_KEY = "url";
  public static final String DB_USER_KEY = "user";

  private static final String DB_DRIVER_DEFAULT = "org.hsqldb.jdbcDriver";          <3>
  private static final Integer DB_POOL_SIZE_DEFAULT = 30;
  private static final String DB_URL_DEFAULT = "jdbc:hsqldb:file:db/conduit;shutdown=true";
  private static final String DB_USER_DEFAULT = "sa";

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> startFuture) throws Exception {

    System.out.println(config().getString(DB_URL_KEY));

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))          <4>
      .put(DB_DRIVER_KEY, config().getString(DB_DRIVER_KEY, DB_DRIVER_DEFAULT))
      .put(DB_USER_KEY, config().getString(DB_USER_KEY, DB_USER_DEFAULT))
      .put(DB_POOL_SIZE_KEY, config().getInteger(DB_POOL_SIZE_KEY, DB_POOL_SIZE_DEFAULT)));

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);          <5>
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);          <5>

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:          <5>
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {
    message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_SUCCESS));          <6>
  }
}

....

<1>  We might as well move the inline EventBus properties to constants while we are doing this
<2>  Make the property keys publicly available
<3>  Create a set of default properties to fall back on
<4>  The syntax, ".put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))," gets the corresponding property from the Verticle's configuration or uses the second argument, our "DEFAULT," value if the value is null
<5>  These values now reference the constants
<6>  This is sort of cheating, but change the return value so we can find out if the test passed

=== Run the Test

[code,shell]
....

mvn clean test

....

Your tests should be passing

[code,shell]
....

[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

....

But we aren't actually doing anything.  Let's get some data from HSQLDB

== Add the Vert.x JDBCClient

Add the Vert.x JDBC

== Creating the Database

=== Step 1: flyway:migrate

Create a folder src/main/resources/db/migration.  Create a new file named "V1_\_create-user-table.sql," in this directory.  Be sure to have 2 underscores between the V1 and the name of the migration.

We can craft a "create table" statement using the values in the expected json returned from our endpoint.

The json outlined in the API:

[code,json]
....
{
  "user": {
    "email": "jake@jake.jake",
    "token": "jwt.token.here",
    "username": "Jacob",
    "bio": "I work at statefarm",
    "image": null
  }
}
....

produces the following table that we can use for authentication

[code,sql]
....
create table if not exists USER ("id" INT IDENTITY PRIMARY KEY ,
  "username" VARCHAR(255) NOT NULL ,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "bio" VARCHAR(255) ,
  "image" VARCHAR(255) ,
  "password" VARCHAR(255) NOT NULL ,
  "password_salt" VARCHAR(255));
....

You might have noticed that there is no Json field, "password_salt."  That column is required by Vert.x Authentication functionality.  We will get to that a bit later.

Create a second migration file, V1.1_\_insert-user.sql in the same folder.  The insert contents are:

[code,sql]
....
insert into USER (  
    "username",
    "email",
    "bio",
    "image",
    "password",
    "password_salt"
    ) values (
    'Jacob',
    'jake@jake.jake',
    'I work at state farm',
    NULL,
    '39DF2CF3B01EA60EF66DE648CE6CE0B5AD3F99DC2E1816F79186741E9A0444C58B17580D8F9D48C0FB033606A8C515DA7C5B6C792B710ECCB9FEF1429D51E3CE',
    'BFB49A9B9CDDDF7C488CB2D84E8DDED8EEC01FFDD26B487DC08E5A4CAB6E4D10');
....

All of these values except the password and the password_salt come from the API documentation.  The password and password salt were generated by Vert.x' JWTAuth framework.   We will cover that shortly.  In the meantime just trust us and use these values.

Run the migration:

[code,shell]
....

mvn flyway:migrate

....

You should see something similar to the following:

[code,shell]
....

[INFO] --- flyway-maven-plugin:5.1.4:migrate (default-cli) @ vertx-conduit-starter ---
[INFO] Flyway Community Edition 5.1.4 by Boxfuse
[INFO] Database: jdbc:hsqldb:file:db/spike (HSQL Database Engine 2.3)
[INFO] Successfully validated 2 migrations (execution time 00:00.010s)
[INFO] Creating Schema History table: "PUBLIC"."flyway_schema_history"
[INFO] Current version of schema "PUBLIC": << Empty Schema >>
[INFO] Migrating schema "PUBLIC" to version 1 - create-user-table
[INFO] Migrating schema "PUBLIC" to version 1.1 - insert-user
[INFO] Successfully applied 2 migrations to schema "PUBLIC" (execution time 00:00.035s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

....

V1_\_create-user-table.sql created our user table, V2_\_insert-user.sql inserted the User from the API docs.  Flyway also created a table that stores information about the migrations

== Step 2: Accessing the Database

=== Vert.x JDBCClient

https://vertx.io/docs/vertx-jdbc-client/java/

The Vert.x JDBC Client dependency can be found on line 54 of your pom.xml:

[code,xml]
....

<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-jdbc-client</artifactId>
</dependency>

....

Add Vert.x JDBC Client to PersistenceVerticle

[code,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";

  private static final String DB_URL_KEY_DEFAULT = "jdbc:hsqldb:file:db/conduit;shutdown=true";          <1>
  private static final String DB_URL_KEY = "url";
  private static final String DB_DRIVER_KEY = "org.hsqldb.jdbcDriver";
  private static final String DB_DRIVER_KEY_DEFAULT = "driver_class";
  private static final String DB_USER_KEY = "user";
  private static final String DB_USER_KEY_DEFAULT = "sa";
  private static final String DB_POOL_SIZE_KEY = "max_pool_size";
  private static final String DB_POOL_SIZE_DEFAULT = "30";

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> startFuture) throws Exception {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(config().getString(DB_URL_KEY), DB_URL_KEY_DEFAULT)
      .put(config().getString(DB_DRIVER_KEY), DB_DRIVER_KEY_DEFAULT)
      .put(config().getString(DB_USER_KEY), DB_USER_KEY_DEFAULT)
      .put(config().getString(DB_POOL_SIZE_KEY), DB_POOL_SIZE_DEFAULT);

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {
    message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_FAILURE));
  }
}

....

Initialize the classes inside of MainVerticle's start method before the Router is initialized and configured:

[souce,java]
....
    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()     <1>
      .put("url", "jdbc:hsqldb:file:db/conduit")     <2>
      .put("driver_class", "org.hsqldb.jdbcDriver")     <3>
      .put("max_pool_size", 30));     <4>

    authProvider = JDBCAuth.create(vertx, jdbcClient);     <5>
    authProvider.setAuthenticationQuery("SELECT PASSWORD, PASSWORD_SALT FROM USER WHERE EMAIL = ?");     <6>
....

<1>  We instantiate the JDBCClient with the "createShared" method.  This will create a single instance that can be shared across Verticles.  We pass in the vertx member variable and a JsonObject for configuration.  Using Json for configuration is the default Vert.x approach.
<2>  The connection url points to the location where we will keep our database.  Flyway will create the "db" folder if it doesn't exist.  It's perfectly fine to keep the database in the project's root directory, but you might want to add "db/" to your .gitignore file.
<3>  We add the appropriate JDBC driver to the configuration.
<4>  This isn't terribly important in development, but we set the connection pool size anyway.
<5>  We instantiate the JDBCAuth AuthProvider with the vertx member variable and the JDBCClient we just created.
<6>  JDBCAuth expects us to authenticate against the "user" and "password" fields.  Our API, however, uses "email" and "password" so we are overriding the default query with one checks the "EMAIL" column instead of the "USER" column.

IMPORTANT: Read 6 above

Delete (or comment out) the stubbed out functionality in the loginHandler method because its time to build the real method.

The first step is to grab the user from the Json posted to our endpoint.

Json:
[code,json]
....
{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}
....

Code that pulls the user from the post:
[code,java]
....
    JsonObject user = context.getBodyAsJson().getJsonObject("user");
    JsonObject authInfo = new JsonObject()
      .put("username", user.getString("email"))     <1>
      .put("password", user.getString("password"));
....

<1>  Vert.x' JDBCAuth expects a parameter, "username," but we only have, "email."  Because of this we updated the query to pull from email, and we are passing in the supplied email with the key, "username."  This is just a workaround.

NOTE: There is an easier way to get Json from a request.  We will get to that shortly.

== Step 3: Authenticate Against the Database

[code,java]
....
    HttpServerResponse response = context.response();     <1>

    authProvider.authenticate(authInfo, ar -> {     <2>
      if (ar.succeeded()) {     <3>
        JsonObject returnValue = new JsonObject()     <4>
        .put("user", new JsonObject()
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
          .put("token", "jwt.token.here")
          .put("username", "jake")
          .put("bio", "I work at statefarm")
          .put("image", ""));

        response.setStatusCode(200)
        .putHeader("Content-Type", "application/json; charset=utf-8")
        .putHeader("Content-Length", String.valueOf(returnValue.toString().length()))
        .end(returnValue.encode());     <5>
      }else{
        response.setStatusCode(200)
          .putHeader("Content-Type", "text/html")
          .end("Authentication Failed: " + ar.cause());
      }
    });
....

<1>  Create an HttpServerResponse for obvious reasons
<2>  This method call, "authProvider.authenticate," does all of the work.  We pass in the authentication info from the request and a lambda to handle success or failure.
<3>  If the user is authenticated we stub out the response becaue we aren't pulling the entire user from the database yet.
<4>  Create a JsonObject and stub it out with expected values.
<5>  JsonObject.encode() encodes the JsonObject as a String.

The complete method is below so that you can check against it:

[code,java]
....
  private void loginHandler(RoutingContext context) {
    JsonObject user = context.getBodyAsJson().getJsonObject("user");
    user.put("username", "placeholder");

    JsonObject authInfo = new JsonObject()
      .put("username", user.getString("email"))
      .put("password", user.getString("password"));
    System.out.println(user);

    HttpServerResponse response = context.response();

    authProvider.authenticate(authInfo, ar -> {
      if (ar.succeeded()) {

        JsonObject returnValue = new JsonObject()
          .put("user", new JsonObject()
            .put("email", "jake@jake.jake")
            .put("password", "jakejake")
            .put("token", "jwt.token.here")
            .put("username", "jake")
            .put("bio", "I work at statefarm")
            .put("image", ""));
        System.out.println(returnValue);

        response.setStatusCode(200)
          .putHeader("Content-Type", "application/json; charset=utf-8")
          .putHeader("Content-Length", String.valueOf(returnValue.toString().length()))
          .end(returnValue.encode());
      }else{
        response.setStatusCode(200)
          .putHeader("Content-Type", "text/html")
          .end("Authentication Failed: " + ar.cause());
      }
    });
  }
....

=== Verify with the MainVerticleTest

[code,shell]
....
mvn clean test
....

It should pass.

== Step 4: Get the User Information from the Database and Return It

Remove the stubbed out "put" methods of our JsonObject "returnValue" so that we have room to work:

[code,java]
....
    authProvider.authenticate(authInfo, ar -> {
      if (ar.succeeded()) {

        JsonObject returnValue = new JsonObject();

        response.setStatusCode(200)
          .putHeader("Content-Type", "application/json; charset=utf-8")
          .putHeader("Content-Length", String.valueOf(returnValue.toString().length()))
          .end(returnValue.encode());
      }else{
        response.setStatusCode(200)
          .putHeader("Content-Type", "text/html")
          .end("Authentication Failed: " + ar.cause());
      }
    });
....

It's probably not a bad idea to run our tests again as a sanity check to make sure the tests are executing correctly.

[code,shell]
....
mvn clean test
....

Should produce failing tests.

= COPY/PASTE from earlier db stuff

== Adding a Database

The first step is to add a Vert.x JDBCClient to the MainVerticle as a class variable:

[source,java]
....
  import io.vertx.ext.jdbc.JDBCClient;
  ...
public class MainVerticle extends AbstractVerticle {

  private JDBCClient jdbcClient;                                   <1>

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()   <2>
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    Router baseRouter = Router.router(vertx);
    ...
....
<1> Create a member variable
<2> Instantiate the JDBClient py passing in our vertx Object and configuration in the form of a JsonObject

== Looking Up the User

We have the endpoint, but it isn't doing anything at the moment.  In order to actually authenticate users we will need to look them up from a database.  To do that we will need to:
* create a database
* prepopulate the database with data
* connect and lookup our user, "jake@jake.jake"

=== Adding a Database

==== HyperSQL
HyperSQL, http://hsqldb.org, is a small relational database that can be accessed in-memory data store and on the file system.  It isn't recommended for production systems, but it is an excellent choice for development.

The database dependencies can be found in the pom.xml

[source,xml]
....
    <!-- Database Dependencies -->
    <dependency>
      <groupId>io.vertx</groupId> 
      <artifactId>vertx-jdbc-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
    </dependency>
....

The first step is to add a Vert.x JDBCClient to the MainVerticle as a class variable:

[source,java]
....
  import io.vertx.ext.jdbc.JDBCClient;
  ...
public class MainVerticle extends AbstractVerticle {

  private JDBCClient jdbcClient;                                   <1>

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()   <2>
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    Router baseRouter = Router.router(vertx);
    ...
....
<1> Create a member variable
<2> Instantiate the JDBClient py passing in our vertx Object and configuration in the form of a JsonObject

==== AuthProvider

Add a JDBCAuth provider and instantiate it by passing in 

[source,java]
....
import io.vertx.ext.auth.jdbc.JDBCAuth;

public class MainVerticle extends AbstractVerticle {

  private JDBCAuth authProvider;

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    authProvider = JDBCAuth.create(vertx, jdbcClient);
....

Instantiate it 
==== JsonObject

[source,java]
....
    JsonObject userLogin = new JsonObject()
      .put("user", new JsonObject()
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
      );

    JsonObject expectedReturn = new JsonObject()
      .put("user", new JsonObject()
        .put("email", "jake@jake.jake")
        .put("password", "jakejake")
        .put("token", "jwt.token.here")
        .put("username", "jake")
        .put("bio", "I work at statefarm")
        .put("image", ""));
....

==== Test Method
[source,java]
....
    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {
      deploymentCheckpoint.flag();

      webClient.post(8080, "localhost", "/")
        .as(BodyCodec.string())
        .sendJsonObject(userLogin, resp -> {
          authenticationCheckpoint.flag();
          assertEquals(200, resp.result().statusCode());
          assertEquals(expectedReturn, resp.result().bodyAsJsonObject());
        });
    }));
....

=== Run the Test

[source,shell]
....
mvn clean test
...
[ERROR] Failures:
[ERROR]   AuthenticationEndpointTest.testSuccessfulAuthentication org.opentest4j.AssertionFailedError: expected: <{"user":{"email":"jake@jake.jake","password":"jakejake","token":"jwt.token.here","username":"jake","bio":"I work at statefarm","image":""}}> but was: <null>
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
....

== Add the Route and Handler

[source,java]
....
    router.route("/api/users/login").handler(this::loginHandler);
....

== Create our Users domain model

[source,java]
....
package io.vertx.thinkster.conduit.domain;

public class User {

  private String email;

  private String token;

  private String username;

  private String bio;

  private String image;

  public User(String email, String token, String username, String bio, String image) {
    this.email = email;
    this.token = token;
    this.username = username;
    this.bio = bio;
    this.image = image;
  }

  @Override
  public String toString() {
    return "User{" +
      "email='" + email + '\'' +
      ", token='" + token + '\'' +
      ", username='" + username + '\'' +
      ", bio='" + bio + '\'' +
      ", image='" + image + '\'' +
      '}';
  }

  public User(String email) {
    this.email = email;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }
}

....

== /api/users/login

Steps

* Create the Users object of our domain model
* Add a new route
* Attach a handler to the route
* Implement the handler
* Validate the required fields
* Extract the posted data
* Lookup the user (we will stub this out for now)
* Return the expected result


Add a new route: 

[code,java]
....
    router.route("/api/users/login").handler(this::loginHandler);
....

Implement loginHandler

[code,java]
....
    User user = new User();
    user.setUsername("vertx-user");
    user.setBio("Mock bio");
    user.setEmail("user@vertx.io");
    user.setToken("token");

    HttpServerResponse response = routingContext.response();
    response
      .putHeader("content-type", "text/html")
      .end(Json.encodePrettily(user));
....

./redeploy.sh

== Postman and Newman
update the variables with "localhost:8080/api"
pass the first Postman test Auth/login

== Handle the actual request values

Create a domain model to handle errors:

[code,java]
....
package io.vertx.thinkster.conduit.domain;

public class ConduitError {

  private Error error;

  public ConduitError() {

    this.error = new Error("Something went wrong");

  }

  public ConduitError(String body) {

    this.error = new Error(body);
  }

  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }

  private class Error {

    private String body;

    public Error(String body) {
      this.body = body;
    }

    public String getBody() {
      return body;
    }

    public void setBody(String body) {
      this.body = body;
    }

  }

}
....

