= Step 1 : Getting Started
:source-highlighter: coderay

== Key Terms in This Step
pom.xml
Fat jar (or Uber jar)
Verticle
JUnit
Vertx JUnit 5 Extension
Checkpoint
Vertx WebClient

== Clone the Vert.x Starter Project

[source,shell]

....

git clone https://github.com/jeremyrdavis/vertx-conduit-starter.git (1)
cd vertx-conduit-starter (2)
rm -Rf .git (3)
git init (4)

....

* This is a basic Vert.x project that we will use as a starting point
* Change into the project directory
* Delete the existing Git repository
* Initialize a new Git repository to hold our changes

=== Create a Remote Repository (Optional, but Recommended)
Keeping a remote copy for yourself is useful while making changes
Create a repository in Github

[source,shell]
....

git remote add origin https://github.com/[YOUR GITHUB NAME]/thinkster-vertx.git
git push -u origin master

....

=== A Few Things About Your pom.xml
Using the text editor of your choice open the pom.xml file.

[source,xml]
....
  <groupId>io.vertx.conduit</groupId>     <1>
  <artifactId>vertx-conduit-starter</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <vertx.version>3.5.2</vertx.version>     
    <main.verticle>io.vertx.starter.MainVerticle</main.verticle>     <2>
  </properties>
....

<1> The starter project contains "Step 0" of this tutorial
<2> This class already exists.  It is where we will begin our work.  This property tells java which file in our fat jar should be run.

=== IDE Time

==== IntelliJ

==== About
https://www.jetbrains.com/idea/

==== Creating a new project
1. Choose "File -> New -> Project From Existing Sources..."
2. Browse to the directory holding your project and choose the directory itself and choose "Open."  This will start an import wizard
3. "Maven" should already be selected in the "Import Project" dialog.  Click, "Next"
4. "Root Directory" should be highlighted with the directory of your project.  Click, "Next"
5. "redhat-jboss-ga" and "techpreview-all-repository" should already be selected.  Click, "Next"
6. "io.vertx.starter:vertx-thinkster:1.0-SNAPSHOT
7.  Be sure to select JDK 1.8.  Click, "Next"
8.  Project name should be "vertx-thinkster."  Click, "Finish"
9.  You can open the project in a new window or use your existing one

We will be using mvn directly for this tutorial.  You can run the following terminal commands in IntelliJ's Terminal window if you like.

==== Eclipse
==== Visual Studio Code

== Real Work!

=== Build and test 

For simplicity's sake we will use maven to build and test.  You are welcome to use your IDE's mechanism if you prefer, but we recommend checking every now again with Maven on the command line just to be sure your IDE hasn't added something magical in the background. 

[source,shell]
....
mvn clean package
....

You should successfully build and pass the default test.

Open up the "target" directory, and you will see 2 jar files.  We will be running our application from the "-fat.jar"

=== Launch our first Verticle

Let's fire up our first verticle!

NOTE: Verticles are the most basic unit of work in Vert.x


[source,shell]
....
mvn clean package
java -jar ./target/vertx-conduit-1.0-SNAPSHOT-fat.jar
....

You should see the following message:

[source,shell]
....
INFO: Succeeded in deploying verticle
....

Open http://localhost:8080.  You should see, "Hello, Vert.x!"

Ctrl + c to stop the server

=== redeploy.sh
Our default project contains 2 redeploy files, "redeploy.sh" and "redeploy.bat," that will keep your application running and redploy when you make changes.

Start your application with the redeploy scripts:
[source,shell]
....
./redeploy.sh or redeploy.bat
....

Open http://localhost:8080/
You should see the same text you saw when running the fat jar, "Hello, Vert.x!"

Open src/main/java/io/vertx/start/MainVerticle.java

Change the "Hello, Vert.x" text to "Hello, Conduit"
Check your browser again.  You should see, "Hello, Conduit"

Stop your application with Ctrl + c

== MainVerticleTest.java

The vertx-conduit-starter project comes with a single Verticle, MainVerticle, and a single unit test, MainVerticleTest.  The complete class is annotated below, but open MainVerticleTest in your IDE (or editor) because we broke the test in the previous section, and it needs to be fixed.

=== Vert.x JUnit 5 Integration
https://vertx.io/preview/docs/vertx-junit5/java/

[code,java]
....
package io.vertx.conduit;

import io.vertx.core.Vertx;     <1>
import io.vertx.ext.web.client.WebClient;     <2>
import io.vertx.ext.web.codec.BodyCodec;     <3>
import io.vertx.junit5.Checkpoint;     <4>
import io.vertx.junit5.VertxExtension;     <5>
import io.vertx.junit5.VertxTestContext;     <6>
import org.junit.jupiter.api.DisplayName;     <7>
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.junit.jupiter.api.Assertions.assertEquals;


@DisplayName("MainVerticle Test")
@ExtendWith(VertxExtension.class)     <8>
class MainVerticleTest {

  @Test
  @DisplayName("Server Started Test")
  void testServerStart(Vertx vertx, VertxTestContext testContext) {     <9>
    WebClient webClient = WebClient.create(vertx);     <10>

    Checkpoint deploymentCheckpoint = testContext.checkpoint();     <11>
    Checkpoint requestCheckpoint = testContext.checkpoint();

    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {     <12>
      deploymentCheckpoint.flag();     <13>

      webClient.get(8080, "localhost", "/")
        .as(BodyCodec.string())
        .send(testContext.succeeding(resp -> {     <14>
          testContext.verify(() -> {     <15>
            assertEquals(200, resp.statusCode());
            assertEquals("Hello, Vert.x!", resp.body());
            requestCheckpoint.flag();     <16>
          });
        }));
    }));
  }


}
....

<1>  We import and use a Vert.x object because we will spin up and run our Verticles within the unit test.  Vert.x is a toolkit unlike application servers or servlet containers.  We won't deploy anything to Vert.x; we run it directly.
<2>  Vert.x WebClient makes it easy to do HTTP request/response interactions with a web server.  It also has advanced features for encoding and decoding Json, error handling, form submission, and other web related things.  It is also really useful for testing our endpoints.  You will see a lot of it in this tutorial.
<3>  BodyCodec encoded and decodes HTTP bodies.
<4>  Vert.x JUnit 5 Extension provides Checkpoint classes that make testing asynchronous code much easier.  When all of the checkpoints are flagged (see 13 and 16 below) the testContext (see 6) will pass the test.
<5>  The Vert.x JUnit 5 Extension provides a TestContext
<6>
<7>  The next few imports are from "org.junit.jupiter.api."  JUnit 5 is a major rewrite of the test framework.  If you haven't checked it out yet the user guide is a great reference:
https://junit.org/junit5/docs/current/user-guide/
Java Magazine also devoted an issue to its' release: http://www.javamagazine.mozaicreader.com/NovDec2016
<8>  In JUnit 5 ExtendWith replaces RunWith.  We are extending with VertxExtension
<9>  We pass a Vertx object and a VertxTestContext object to each test method.  These are supplied by the VertxExtension
<10>  We instantiate the WebCliet to test our endpoint.
<11>  Here we instantiate 2 checkpoints.  We will use the first to verify that the server started.  The second will signal the end of our test.
<12>  Two things of note occur on this line.  First, we deploy our Verticle from the test.  This gives us the ability to swap out components because we will eventually have more than one and control configuration from our unit tests.  The second thing to notice is the callback, "testContext.succeeding."  VertxExtension to JUnit provides "failing" and "succeeding" callbacks and the void method "completeNow" that signal the end of the test.  The "succeeding" method takes a callback as its' argument and ends the test based on the result.
<13>  We flag our first checkpoint because the Verticle is successfully deployed.
<14>  We send our post data to the endpoint using testContext.succeeding.
<15>  We use testContext.verify to check the values returned from our endpoint.
<16>  We flag our second Checkpoint to signal the end of the test.

