= Step 05 : Adding an In Memory Database
:source-highlighter: prettify
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Summary

Now that we have stubbed out the Register User methods it is time to do some real work.  In this step we will create a database for our application and persist a User

== KeyTerms in this Step

* Flyway database migration tool: https://flywaydb.org
* HyperSQL http://hsqldb.org/

* io.vertx.ext.jdbc.JDBCClient

=== Flyway

Flyway is a databse migration tool.  Programmatic database migrations were introduced by Ruby on Rails. Flyway is a Java application and fits nicely into the Java build ecosystem, but it will feel familiar to anyone who has used Rails before

Flyway has a command line tool, a Java API that can be executed from your application, and a Maven plugin.  We will use the maven plugin and the Java API in our Unit Tests.  There are only a couple of commands that you have to know to use Flyway

You can run the Flyway Maven commands like this:

[code,shell]
....

mvn flyway:migrate

....

The Java API is similarly straightforward:

[code,java]
....

    Flyway flyway = Flyway.configure().dataSource(DB_URL_TEST, DB_USER_TEST, null).load();
    flyway.migrate();

....

NOTE: If for some reason something goes wrong with a Flyway migration you need to run "mvn flyway:repair" before rerunning the migration.  You can also safely delete the enire "db" folder, which will be in the root of your project, and re-run "mvn flyway:migrate"

==== Properties, Dependencies, and Plugin

The Flyway properties on line 18 of the pom.xml, the dependency on line 92, and the plugin on line 115.

===== Properties

[code,xml]
....

    <!-- Flyway Database Migrations -->
    <flyway.url>jdbc:hsqldb:file:db/conduit</flyway.url>     <1>
    <flyway.driver>org.hsqldb.jdbcDriver</flyway.driver>     <2>
    <flyway.locations>filesystem:src/main/resources/db/migration</flyway.locations>     <3>

....

<1> The filesystem location of our HyperSQL database
<2> The JDBC driver
<3> The location where we will keep our migration scripts.  This is the default location for the Java API

===== Dependency

The flyway-core dependency is required to use Flyway in Java classes.  We will be using it to create tables and populate data in memory for use in our Unit Tests

[code,xml]
....

<dependency>
  <groupId>org.flywaydb</groupId>
  <artifactId>flyway-core</artifactId>
  <version>5.2.0</version>
</dependency>

....

===== Plugin

The Maven plugin makes it easy to create tables and populate data before running the application

[code,xml]
....

<plugin>
  <groupId>org.flywaydb</groupId>
  <artifactId>flyway-maven-plugin</artifactId>
  <version>5.1.4</version>
</plugin>
        
....

=== HyperSQL (HSQLDB)

HyperSQL, http://hsqldb.org, is a small relational database that can be store data in-memory or on the file system.  We will use both methods in ths project.

HSQLDB isn't recommended for production systems, but it is an excellent choice for development.

The database dependencies can be found in the pom.xml on line 64

[source,xml]
....
    <!-- Database Dependencies -->
    <dependency>
      <groupId>io.vertx</groupId> 
      <artifactId>vertx-jdbc-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
    </dependency>
....

== Fail a Test

First things first we need to fail a test

=== Database Configuration

The Flyway section of this document mentioned that we will be using HSQLDB's File System and In-Memory modes.  HSQLDB's in-memory mode gives us the ability to create the database in memory before every test

We will share the database properties across multiple objects so we should keep those in a single location.  Create a new class, "DatabaseProps," in the "io.vertx.conduit.persistence" package:

src/main/java/io/vertx/conduit/persistence/DatabaseProps.java
[code,java]
....

package io.vertx.conduit.persistence;

public class DatabaseProps {

  protected static final String DB_DRIVER_KEY = "driver_class";
  protected static final String DB_POOL_SIZE_KEY = "max_pool_size";
  protected static final String DB_URL_KEY = "url";
  protected static final String DB_USER_KEY = "user";

  protected static final String DB_DRIVER_DEFAULT = "org.hsqldb.jdbcDriver";
  protected static final Integer DB_POOL_SIZE_DEFAULT = 30;
  protected static final String DB_URL_DEFAULT = "jdbc:hsqldb:file:db/conduit;shutdown=true";
  protected static final String DB_USER_DEFAULT = "sa";

}

....

Let's do the same for test properties and create a class, "TestDatabaseProps," in test directory:

src/test/java/io/vertx/conduit/persistence/TestDatabaseProps.java
[code,java]
....

package io.vertx.conduit.persistence;

public class TestDatabaseProps {

  protected static final String DB_URL_TEST = "jdbc:hsqldb:mem:testdb;db_close_delay=-1";
  protected static final String DB_DRIVER_TEST = "org.hsqldb.jdbcDriver";
  protected static final String DB_USER_TEST = "sa";
  protected static final Integer DB_POOL_SIZE_TEST = 30;

}

....

=== And Queries

We will externalize the queries as well.  Create a file SQLQueries in the persistence package:

src/main/java/io/vertx/conduit/persistence/SQLQueries.java
[code,java]
....

package io.vertx.conduit.persistence;

public class SQLQueries {

  public static final String SQL_REGISTER_USER = "insert into USER (\"username\",\"email\",\"bio\",\"password\") values (?, ?, ?, ?);";
  public static final String SQL_SELECT_USER_BY_EMAIL = "select * from USER where \"email\" = ?";

}

....

=== Update the Unit Test

Now we can update PersistenceVerticleTest:

src/main/test/io/vertx/conduit/persistence/PersistenceVerticleTest
[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static io.vertx.conduit.persistence.DatabaseProps.*;          <1>
import static io.vertx.conduit.persistence.TestDatabaseProps.*;         <2>

@DisplayName("Persistence Event Bus Tests")
@ExtendWith(VertxExtension.class)
public class PersistenceVerticleTest {

  private JDBCClient jdbcClient;         <3>

  @BeforeEach
  void setUp(Vertx vertx, VertxTestContext testContext) {          <4>

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()         <5>
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST));

    Flyway flyway = Flyway.configure().dataSource(DB_URL_TEST, DB_USER_TEST, null).load();         <6>
    flyway.migrate();         <7>

    testContext.completeNow();         <8>
  }

  @Test
  @DisplayName("Register User Test") 
  @Timeout(2000)
  void testServerRegisterUserOverEventBus(Vertx vertx, VertxTestContext testContext) {

    Checkpoint deploymentCheckpoint = testContext.checkpoint();
    Checkpoint replyCheckpoint = testContext.checkpoint();

    User user = new User("user1@user.com", null, "user1", "user1's bio", null);

    JsonObject message = new JsonObject()
      .put(PERSISTENCE_ACTION, PERSISTENCE_ACTION_REGISTER)         
      .put("user", Json.encode(user));

    vertx.deployVerticle(new PersistenceVerticle(), testContext.succeeding(id -> {         
      deploymentCheckpoint.flag();          
      vertx.eventBus().send(PERSISTENCE_ADDRESS, message, testContext.succeeding(ar -> {          
        testContext.verify(() -> {          
          assertEquals(PERSISTENCE_OUTCOME_SUCCESS, ((JsonObject) ar.body()).getString("outcome"));
          replyCheckpoint.flag();        
          testContext.completeNow();        
        });
      }));
    }));
  }
}

....

<1>  Import the DatabaseProps constants
<2>  Import the TestDatabaseProps constants
<3>  We will need a local JDBCClient to query the database and verify the insert worked
<4>  We have added a @BeforeEach method that will run before each test and run the database migrations  
<5>  Instantiate the JDBCClient with the constants in TestDatabaseProps
<6>  Instantiate our Flyway object with the test properties
<7>  Perform the database migration creating our user table (we will create the migration in the next step
<8>  Be sure to let JUnit and the VertxExtension that the @Before method is finished!

IMPORTANT: The Unit Test won't exit without the testContext.completeNow() call.  Keep this in mind if you ever find yourself waiting for your Unit Test to complete

=== Create the Migration

Create a folder src/main/resources/db/migration.  This is the default Flyway location, and there is no compelling reason to change it

Create a new file named "V1_\_create-user-table.sql," in this directory.  Be sure to have 2 underscores between the V1 and the name of the migration

We can craft a "create table" statement using the values from the json outlined in the API.  The Registration endpoint expects a Post request at "/api/users" with the following body:

[code,json]
....

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

....

Our API defines the following response:

[code,json]
....

{
  "user": {
    "email": "jake@jake.jake",
    "token": "jwt.token.here",
    "username": "jake",
    "bio": "I work at statefarm",
    "image": null
  }
}

....

The combined values produce the following table which becomes our V1 migration:

src/main/java/resources/db/migration/V1_\_create-user-table.sql

[code,sql]
....

create table if not exists USER ("id" INT IDENTITY PRIMARY KEY ,
  "username" VARCHAR(255) NOT NULL ,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "bio" VARCHAR(255) ,
  "image" VARCHAR(255) ,
  "password" VARCHAR(255) NOT NULL);

....

Run the test to verify that the migration works:

[code,shell]
....

mvn clean test -Dtest=PersistenceVerticleTest          <1>

....

<1> The flag "-Dtest=PersistenceVerticleTest" limits execution to only PersistenceVerticleTest

The test will fail, but check the logs for a message about the migration:

[code,shell]
....

INFO: Migrating schema "PUBLIC" to version 1 - create-user-table
Oct 13, 2018 6:44:50 AM org.flywaydb.core.internal.command.DbMigrate logSummary
INFO: Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.028s)          <1>
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.674 s <<< FAILURE! - in io.vertx.conduit.persistence.NewPersistenceVerticleTest
[ERROR] testServerRegisterUserOverEventBus{Vertx, VertxTestContext}  Time elapsed: 0.672 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at io.vertx.conduit.persistence.NewPersistenceVerticleTest.testServerRegisterUserOverEventBus(NewPersistenceVerticleTest.java:46)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   NewPersistenceVerticleTest.testServerRegisterUserOverEventBus:46 expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

....

<1>  The log, "INFO: Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.028s)" is what we are looking for

=== Verify the Insert

There is one last step: we need to verify that our user was saved to the database.  Add the following code to PersistenceVerticleTest:

src/main/test/io/vertx/conduit/persistence/PersistenceVerticleTest
[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.conduit.model.User;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.json.Json;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.SQLConnection;
import io.vertx.junit5.Checkpoint;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static io.vertx.conduit.SQLQueries.SQL_SELECT_USER_BY_EMAIL;
import static io.vertx.conduit.persistence.DatabaseProps.*;
import static io.vertx.conduit.persistence.PersistenceVerticle.*;
import static io.vertx.conduit.persistence.TestDatabaseProps.*;

@DisplayName("Persistence Event Bus Tests")
@ExtendWith(VertxExtension.class)
public class PersistenceVerticleTest {

  private JDBCClient jdbcClient;


  @BeforeEach
  void setUp(Vertx vertx, VertxTestContext testContext) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST));

    Flyway flyway = Flyway.configure().dataSource(DB_URL_TEST, DB_USER_TEST, null).load();
    // Run the migration
    flyway.migrate();

    testContext.completeNow();
  }

  @Test
  @DisplayName("Register User Test")
  @Timeout(10000)
  void testServerRegisterUserOverEventBus(Vertx vertx, VertxTestContext testContext) {

    Checkpoint deploymentCheckpoint = testContext.checkpoint();
    Checkpoint replyCheckpoint = testContext.checkpoint();

    User user = new User("user1@user.com", null, "user1", "user1's bio", null, "password");

    JsonObject message = new JsonObject()
      .put(PERSISTENCE_ACTION, PERSISTENCE_ACTION_REGISTER)
      .put("user", Json.encode(user));

    JsonObject eventBusDeploymentConfig = new JsonObject()          <1>
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST);


    vertx.deployVerticle(new PersistenceVerticle(), new DeploymentOptions().setConfig          <2>(eventBusDeploymentConfig),testContext.succeeding(id -> {
      deploymentCheckpoint.flag();
      vertx.eventBus().send(PERSISTENCE_ADDRESS, message, testContext.succeeding(ar -> {
        testContext.verify(() -> {
    
          // query database to verify insert
          jdbcClient.getConnection(conn ->{          <3>
            if (conn.failed()) {
              Assertions.assertTrue(conn.succeeded());          <4>
              testContext.completeNow();          <5>
            }
            final SQLConnection connection = conn.result();          <6>

            connection.queryWithParams(SQL_SELECT_USER_BY_EMAIL,          <7> 
               new JsonArray().add(user.getEmail()),          <8> 
               rs -> {
                if (rs.failed()) {
                  Assertions.assertTrue(rs.succeeded());          <9>
                  testContext.completeNow();          <10>
                }
                Assertions.assertEquals(1, rs.result().getNumRows());          <11>
                System.out.println(rs.result().getResults().get(0).encode());
              });
            });

          Assertions.assertEquals(PERSISTENCE_OUTCOME_SUCCESS, ((JsonObject) ar.body()).getString("outcome"));
          replyCheckpoint.flag();
          testContext.completeNow();
        });
      }));
    }));
  }

}

....

<1>  Create a JsonObject to pass the configuration for the EventBus
<2>  Add the configuration as the second parameter when deploying the PersistenceVerticle
<3>  Use the jdbcClient to get a database connection
<4>  If we can't get a connection we can fail the test
<5>  Be sure to let the VertxExtension know we are done!
<6>  The SQLConnection is the result of getConnection
<7>  Use SQLConnection's queryWithParams method to retrieve our new User by email.  
<8>  The queryWithParams method gets the parameters to use in the query from a JsonArray.  Add the User's email to a new JsonArray
<9>  If there are no results we can fail the test
<10>  Be sure to let the VertxExtension know we are done!
<11>  Verify that we have a single result



=== Pass the Test

We need to add the JDBC constants to PersistenceVerticle:

src/main/java/io/vertx/conduit/persistence/PersistenceVerticle.java
[code,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";          <1>
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";

  public static final String DB_DRIVER_KEY = "driver_class";          <2>
  public static final String DB_POOL_SIZE_KEY = "max_pool_size";
  public static final String DB_URL_KEY = "url";
  public static final String DB_USER_KEY = "user";

  private static final String DB_DRIVER_DEFAULT = "org.hsqldb.jdbcDriver";          <3>
  private static final Integer DB_POOL_SIZE_DEFAULT = 30;
  private static final String DB_URL_DEFAULT = "jdbc:hsqldb:file:db/conduit;shutdown=true";
  private static final String DB_USER_DEFAULT = "sa";

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> startFuture) throws Exception {

    System.out.println(config().getString(DB_URL_KEY));

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))          <4>
      .put(DB_DRIVER_KEY, config().getString(DB_DRIVER_KEY, DB_DRIVER_DEFAULT))
      .put(DB_USER_KEY, config().getString(DB_USER_KEY, DB_USER_DEFAULT))
      .put(DB_POOL_SIZE_KEY, config().getInteger(DB_POOL_SIZE_KEY, DB_POOL_SIZE_DEFAULT)));

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);          <5>
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);          <5>

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:          <5>
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {
    message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_SUCCESS));          <6>
  }
}

....

<1>  We might as well move the inline EventBus properties to constants while we are doing this
<2>  Make the property keys publicly available
<3>  Create a set of default properties to fall back on
<4>  The syntax, ".put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))," gets the corresponding property from the Verticle's configuration or uses the second argument, our "DEFAULT," value if the value is null
<5>  These values now reference the constants
<6>  This is sort of cheating, but change the return value so we can find out if the test passed

=== Run the Test

[code,shell]
....

mvn clean test

....

Your tests should be passing

[code,shell]
....

[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

....

But we aren't actually doing anything.  Let's get some data from HSQLDB

== Add the Vert.x JDBCClient

Add the Vert.x JDBClient to PersistenceVerticle and 

[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.conduit.model.User;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;          <1>
import io.vertx.ext.sql.UpdateResult;

import static io.vertx.conduit.persistence.SQLQueries.SQL_REGISTER_USER;
import static io.vertx.conduit.persistence.DatabaseProps.*;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";

  private JDBCClient jdbcClient;          <2>

  @Override
  public void start(Future<Void> startFuture) throws Exception {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()          <3>
      .put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))
      .put(DB_DRIVER_KEY, config().getString(DB_DRIVER_KEY, DB_DRIVER_DEFAULT))
      .put(DB_USER_KEY, config().getString(DB_USER_KEY, DB_USER_DEFAULT))
      .put(DB_POOL_SIZE_KEY, config().getInteger(DB_POOL_SIZE_KEY, DB_POOL_SIZE_DEFAULT)));

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {
    message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_SUCCESS));
  }
}

....

<1>  Import "io.vertx.ext.jdbc.JDBCClient"
<2>  Declare a member variable
<3>  Initialize the member variable.  The method "config().getString(DB_URL_KEY, DB_URL_DEFAULT))" first checks the config property of the Verticle (which is coming from the Unit Test in this case) or uses the default if the property isn't in the config

== Insert the User in the Database

This is the last change we need to make.  Build out the "registerUser" method with the following:

[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.conduit.model.User;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.UpdateResult;

import static io.vertx.conduit.persistence.SQLQueries.SQL_REGISTER_USER;
import static io.vertx.conduit.persistence.DatabaseProps.*;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> startFuture) throws Exception {

    System.out.println(config().getString(DB_URL_KEY));

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))
      .put(DB_DRIVER_KEY, config().getString(DB_DRIVER_KEY, DB_DRIVER_DEFAULT))
      .put(DB_USER_KEY, config().getString(DB_USER_KEY, DB_USER_DEFAULT))
      .put(DB_POOL_SIZE_KEY, config().getInteger(DB_POOL_SIZE_KEY, DB_POOL_SIZE_DEFAULT)));

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {

    JsonObject userJson = new JsonObject(message.body().getString("user"));          <1>
    User user = new User(userJson);          <2>

    jdbcClient.updateWithParams(SQL_REGISTER_USER, new JsonArray()          <3>
      .add(user.getUsername())
      .add(user.getEmail())
      .add(user.getBio())
      .add(user.getPassword())
      , res -> {
      if (res.succeeded()) {
        UpdateResult updateResult = res.result();          <4>
        System.out.println("No. of rows updated: " + updateResult.getUpdated());
        if (updateResult.getUpdated() >= 1) {          <5>
          message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_SUCCESS));
        }else{
          message.fail(1, "Error: " + res.cause().getMessage());          <6>
        }
      } else {
        message.fail(1, "Error: " + res.cause().getMessage());
      }

    });
  }
}

....

<1>  Get the JsonObject representing the User to register from the message
<2>  Create an instance of our domain model User from the JsonObject
<3>  Insert the User with the "updateWithParams" method.  Even though the method is named, "update," it will execute inserts
<4>  Get the result of the update
<5>  Verify that a record was created and return a successful outcome if it was
<6>  If the insert didn't work return a failure message.  The message.fail() method requires a number.  We will implement a more elegant solution in a moment

Run the test:

[code,shell]
....

mvn clean test -Dtest=NewPersistenceVertilceTest

....

The test should pass.  We are now making a round trip to the database.

[code,shell]
....

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.954 s - in io.vertx.conduit.persistence.PersistenceVerticleTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

....


== Wrapping Up

Create an Enum to store our error codes, "PersistenceErrorCodes."  Because the message.fail() method requires an error number we will use the ordinal of the Enum value as the error code

src/main/java/io/vertx/conduit/persistence/PersistenceErrorCodes.java
[code,java]
....

package io.vertx.conduit.persistence;

public enum PersistenceErrorCodes {

  DB_CONNECTION_ERROR("Database Connection Error: "),          <1>
  DB_INSERT_FAILURE("Insert Failed: ");

  private final String message;          <2>

  private PersistenceErrorCodes(String msg){          <3>
    this.message = msg;
  }

}

....

<1>  Each value representing an error
<2>  Each value will have its' own message
<3>  The message is set only once

Now update PersistenceVerticle with the PersistenceErrorCodes:

[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.conduit.model.User;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.UpdateResult;

import static io.vertx.conduit.persistence.SQLQueries.SQL_REGISTER_USER;
import static io.vertx.conduit.persistence.DatabaseProps.*;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> startFuture) throws Exception {

    System.out.println(config().getString(DB_URL_KEY));

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))
      .put(DB_DRIVER_KEY, config().getString(DB_DRIVER_KEY, DB_DRIVER_DEFAULT))
      .put(DB_USER_KEY, config().getString(DB_USER_KEY, DB_USER_DEFAULT))
      .put(DB_POOL_SIZE_KEY, config().getInteger(DB_POOL_SIZE_KEY, DB_POOL_SIZE_DEFAULT)));

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {

    JsonObject userJson = new JsonObject(message.body().getString("user"));
    User user = new User(userJson);

    jdbcClient.updateWithParams(SQL_REGISTER_USER, new JsonArray()
      .add(user.getUsername())
      .add(user.getEmail())
      .add(user.getBio())
      .add(user.getPassword())
      , res -> {
      if (res.succeeded()) {
        UpdateResult updateResult = res.result();
        System.out.println("No. of rows updated: " + updateResult.getUpdated());
        if (updateResult.getUpdated() >= 1) {
          message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_SUCCESS));
        }else{
          message.fail(
            PersistenceErrorCodes.DB_INSERT_FAILURE.ordinal(),           <1>
            PersistenceErrorCodes.DB_INSERT_FAILURE  + res.cause().getMessage());          <2>
        }
      } else {
        message.fail(
          PersistenceErrorCodes.DB_CONNECTION_ERROR.ordinal(),          <1>
          PersistenceErrorCodes.DB_CONNECTION_ERROR + res.cause().getMessage());          <2>
      }

    });
  }
}

....

<1>  We use the error codes' ordinal as our error number
<2>  We use the base message from the Enum and concatenate the message from the result 