= Step 02 : REST Basics with Vert.x-Web
:source-highlighter: prettify
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Key Terms in This Step
* Future<Void>
* Router
* RoutingContext

== Vert.x Core

Vert.x' core functionality contains an HTTP server.  The example app you cloned spins one up on port 8080 and returns a simple "Hello, Vert.x" which we changed to "Hello, Conduit!"

Just to refresh your memory the code is:

[source,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start() {
    vertx.createHttpServer()
        .requestHandler(req -> req.response().end("Hello, Conduit!"))
        .listen(8080);
  }

}

....

Most applications need more than a single endpoint saying, "Hello," and that's where Vert.x Web comes in.

== Vert.x-Web

https://vertx.io/docs/vertx-web/java/

We will be using Vert.x-Web to build our endpoints.  

Vert.x-Web is one of many Vert.x modules that extend the core toolkit.  The dependency already in your pom.xml.  You can see it on line 46:

[source,xml]
....

<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web</artifactId>
</dependency>

....

Vert.x-Web is as a Swiss Army Knife for building modern, scalable, web apps.  Vert.x core provides a fairly low level set of functionality for handling HTTP, and for some applications that will be sufficient.  Vert.x-Web adds functionality for building real web applications and is especially awesome for building REST APIs and REST based microservices.

Vert.x-Web is influenced by Express in the NodeJS world and Sinatra in the Ruby world so if you have used either of those projects you will feel right at home. 

=== Vert.x-Web Router

Vert.x-Web contains a "Router" that maps URLs to Java methods.  Our initial code uses Vert.x's core HTTP server to return a single endpoint.  We will update our MainVerticle class to use the Vert.x-Web Router instead.

==== Future<Void>

The first thing we will do is to make sure that our Router is correctly set up and working when we start the application.  We will pass an io.vertx.core.Future Object to MainVerticle's start() method:

WARNING: Your IDE will probably automatically import classes while you are typing.  Make sure that the imported classes are the one in the examples.  Your IDE may not grab the correct "Future."

[source,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;          <1>

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Future<Void> startFuture) {
    vertx.createHttpServer()
        .requestHandler(req -> req.response().end("Hello, Conduit!"))
        .listen(8080);
    startFuture.complete();
  }

}

....

<1>  Be sure that you import "io.vertx.core.Future"

In our next step we will check with our future to verify that the Router is working correctly.

==== Vert.x-Web Router

A Router is one of the core concepts of Vert.x-Web. It’s an object which maintains zero or more Routes.  A router takes an HTTP request and finds the first matching route for that request, and passes the request to that route

The route can have a handler associated with it, which then receives the request. You then do something with the request, and then, either end it or pass it to the next matching handler

Now its time to add the Router to our start method just above the existing code and use it to handle all HTTP reqeusts:

[source,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.ext.web.Router;          <1>

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Future<Void> startFuture) {

    Router baseRouter = Router.router(vertx);          <2>
    baseRouter.route("/").handler(this::indexHandler);          <3>

    vertx
      .createHttpServer()
      .requestHandler(baseRouter::accept)          <4>
      .listen(8080, result -> {          <5>
      if (result.succeeded()) {          
        startFuture.complete();         <6>
      }else {
        startFuture.fail(result.cause());          <7>
      }
    });
  }

}

....

<1>  Import the Router from the "io.vertx.ext.web" package.  Be sure to use this package.  There is another Router in the "io.vertx.reactivex.ext.web" package; we don't want that one yet
<2>  Instantiate the Router
<3>  Handle the root endpoint, "/"  We haven't created the handler yet; that's in the next step.  You may also have noticed that we named our Router instance, "baseRouter," which suggests we may eventually have more than one
<4>  Our previous method passed a lambda as the argument to the requestHandler method.  We have swapped it out with our baseRouter.  Vert.x will now pass all HTTP requests to our baseRouter
<6>  If we successfully attach the Router we succeed
<7>  Otherwise we fail


==== Handling Routes (indexHanlder)

Obviously, our code won't compile at the moment because we don't have a method, "indexHandler."  So let's create that method:

[source,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.http.HttpServerResponse;          <1>
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Future<Void> startFuture) {

    Router router = Router.router(vertx);
    router.route("/").handler(this::indexHandler);

    vertx.createHttpServer()
        .requestHandler(req -> req.response().end("Hello, Conduit!"))
        .listen(8080);
    startFuture.complete();
  }

  private void indexHandler(RoutingContext routingContext) {          <2>
    HttpServerResponse response = routingContext.response();          <3>
    response
      .putHeader("Content-Type", "text/html")          
      .end("Hello Conduit!");          <4>
  }

}

....


<1>  Make sure you or your IDE imports "io.vertx.core.http.HttpServerResponse"
<2>  We pass in an Object "RoutingContext" to our method.   A RoutingContext represents the context for the handling of a request in Vert.x-Web.  A new instance is created for each HTTP request that is received in the Router.accept(HttpServerRequest) of the router.  The same instance is passed to any matching request or failure handlers during the routing of the request or failure.  The context provides access to the HttpServerRequest and HttpServerResponse and allows you to maintain arbitrary data that lives for the lifetime of the context such as the Session, cookies and body for the request.  Contexts are discarded once they have been routed to the handler for the request.
<3> We get the response
<4> Set the Content-Type of our response and send the body, "Hello, Conduit!"

Let's run MainVerticleTest to make sure we didn't break anything.  You can use your IDE of course, but for the tutorial we will use Maven directly.

[source,shell]
....

mvn clean test

....

The test should pass.

[source,shell]
....

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.vertx.conduit.MainVerticleTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.607 s - in io.vertx.conduit.MainVerticleTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

....



 
