= Step 02 : REST Basics with Vert.x-Web
:source-highlighter: coderay

== Vert.x-Web

https://vertx.io/docs/vertx-web/java/

We will be using Vert.x-Web to build our endpoints.  

Vert.x-Web is in the vertx-conduit-starter pom.xml on line 36:

[source,xml]
....
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web</artifactId>
</dependency>
....

Vert.x-Web is as a Swiss Army Knife for building modern, scalable, web apps.  Vert.x core provides a fairly low level set of functionality for handling HTTP, and for some applications that will be sufficient.  Vert.x-Web adds functionality for building real web applications and is especially awesome for building REST APIs and REST based microservices.

Vert.x-Web is influenced by Express in the NodeJS world and Sinatra in the Ruby world so if you have used either of those projects you will feel right at home. 

MainVerticle.java currently creates an HTTP server, listens on port 8080 and returns "Hello Vert.x!" using the Vert.x's core HTTP functionality.  Since we will be using the Vert.x-Web package our first step is to delete this basic implementation and begin building our APIs.

=== Vert.x-Web Router

Vert.x-Web contains a "Router" that maps URLs to Java methods.  Our first step is to add the Router to our start method.

[source,java,linenums]
....
    import io.vertx.ext.web.Router; <1>
    ...
    Router router = Router.router(vertx); <2>
    router.route("/").handler(this::indexHandler); <3>
....

<1> Import the Routerfrom the "io.vertx.ext.web" package.  There is another Router in the "io.vertx.reactivex.ext.web" package; we don't want that one yet
<2> Instantiate the Router
<3> Handle the root endpoint, "/"

The next step is to delegate handling the request to our router:

[source,java]
....

    // Create the HTTP server and pass the "accept" method to the request handler.
    vertx
      .createHttpServer()
      .requestHandler(router::accept)
      .listen(8080, result -> {
        if (result.succeeded()) {
          future.complete();
        }else {
          future.fail(result.cause());
        }
      });
....


Obviously, this code won't compile because we don't have a method, "indexHandler."  So let's create that method:

[source,java]
....
  private void indexHandler(RoutingContext routingContext) { <1>
    HttpServerResponse response = routingContext.response(); <2>
    response
      .putHeader("content-type", "text/html")                <3>
      .end("Hello CodeOne!");                                <4>
  }
....


<1> We pass in an Object "RoutingContext" to our method.   A RoutingContext represents the context for the handling of a request in Vert.x-Web.  A new instance is created for each HTTP request that is received in the Router.accept(HttpServerRequest) of the router.  The same instance is passed to any matching request or failure handlers during the routing of the request or failure.  The context provides access to the HttpServerRequest and HttpServerResponse and allows you to maintain arbitrary data that lives for the lifetime of the context such as the Session, cookies and body for the request.  Contexts are discarded once they have been routed to the handler for the request.
<2> We create the response
<3> Set the Content-Type of our response
<4> Set the body of our response

 
