= Step 1 : Getting Started
:source-highlighter: coderay

== Clone the Vert.x Starter Project
[source,shell]
----
git clone https://github.com/vert-x3/vertx-maven-starter.git (1)
mv vertx-maven-starter/ thinkster-vertx (2)
cd vertx-junit5-spike (3)
rm -Rf .git (4)
git init (5)
----
1. This is a basic Vert.x project that we will use as a starting point
2. Rename the basic project to "thinkster-vertx."  You can use a different name of course, but make sure you stay consistent during the workshop.
3. Change into the project directory
4. Delete the existing Git repository
5. Initialize a new Git repository to hold our changes

=== Create a Remote Repository (Optional, but Recommended)
Keeping a remote copy for yourself is useful while making changes
Create a repository in Github
[source,shell]
....
git remote add origin https://github.com/[YOUR GITHUB NAME]/thinkster-vertx.git
git push -u origin master
....

=== Update the pom
Using the text editor of your choice:
1. Open up pom.xml
2. Change the groupId to: io.vertx.thinkster
3. Change the artifactId to : vertx-thinkster
4. Change the main.verticle to: <main.verticle>io.vertx.thinkster.MainVerticle</main.verticle>

The result should look like this:
[source,xml]
....
<groupId>io.vertx.thinkster</groupId>
  <artifactId>vertx-thinkster</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <vertx.version>3.5.2</vertx.version>
    <main.verticle>io.vertx.thinkster.MainVerticle</main.verticle>
  </properties>
....

=== IDE Time

==== IntelliJ
==== Eclipse
==== Visual Studio Code

=== Real Work!
[source,shell]
....
git checkout -b step-01
....

Open pom.xml and change the package and project name:
[source,xml]
....
  <groupId>io.vertx.conduit</groupId>
  <artifactId>vertx-conduit</artifactId>
  <version>1.0-SNAPSHOT</version>
....

== Launch our first Verticle

=== Compile
[source,shell]
....
mvn clean package
java -jar ./target/vertx-conduit-1.0-SNAPSHOT-fat.jar
....

Open http://localhost:8080/
You should see, "Hello, Vert.x!"
Ctrl + c to stop the server

=== redeploy.sh
./redeploy.sh or redeploy.bat
Open src/main/java/io/vertx/start/MainVerticle
Open http://localhost:8080/
You should see, "Hello, Vert.x!"
Change the "Hello, Vert.x" text to "Hello, Conduit"
Check your browser again.  You should see, "Hello, Conduit"
Ctrl + c to quit the process

== Refactor the package name
Change the package structure to "io.vertx.thinkster.conduit"
NOTE: Be sure to change the redeploy file
