= Step 06 : Authentication with JWT
:source-highlighter: coderay
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Summary

Now that we are authenticating users against the database and createing JWT tokens we can lock down our endpoints.  The first protected endpoint we will implement is  "GET /api/user" which requires JWT authentication and returns the authenticated user, in our case "jake":

[code,json]
....

    {
        "user": {
        "email": "jake@jake.jake",
        "token": "jwt.token.here",
        "username": "jake",
        "bio": "I work at statefarm",
        "image": null
        }
    }

....

== KeyTerms in this Step

JWT

== Failure Time!

Create a new class JWTAuthenticationTest in our test package, with a single test method, "GetCurrentUserEndpointTest" :

[code,java]
....

package io.vertx.conduit;

import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.client.WebClient;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DisplayName("Authentication Endpoint Tests")
@ExtendWith(VertxExtension.class)
public class AuthenticationEndpointTest {

  @Test
  public void testSuccessfulAuthentication(Vertx vertx, VertxTestContext testContext){
    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {
      WebClient webClient = WebClient.create(vertx);
      webClient.post(8080, "localhost", "/api/users/login")
        .sendJsonObject(new JsonObject()          <1>
        .put("user", new JsonObject()     
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
        ), response -> testContext.verify(() -> {          <2>
        JsonObject user = response.result().bodyAsJsonObject().getJsonObject("user");          <3>
          System.out.println(user.encodePrettily());
          assertEquals(200, response.result().statusCode());
        assertEquals("jake@jake.jake", user.getString("email"));
        assertEquals("jakejake", user.getString("password"));
        assertNotNull( user.getString("token"));
        assertEquals("jake", user.getString("username"));
        assertEquals("I work at statefarm", user.getString("bio"));
        assertEquals("", user.getString("image"));
        testContext.completeNow();
      }));
    }));
  }
}


....