= Step04: The Vert.x Event Bus
:source-highlighter: prettify
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Summary

In this step we will create a Verticle to handle our database functionality and use Vert.x Event Bus to communicate with it from our MainVerticle.

== Introducing the Vert.x Event Bus

The event bus is the nervous system of Vert.x.  

There is a single event bus instance for every Vert.x instance.  The event bus allows different parts of your application to communicate with each other irrespective of what language they are written in

It can even be bridged to allow client side JavaScript running in a browser to communicate on the same event bus

Vert.x' event bus supports publish/subscribe, point to point, and request-response messaging.

The event bus API is very simple. It basically involves registering handlers, unregistering handlers and sending and publishing messages.

=== Addressing
Messages are sent on the event bus to an address.

Vert.x doesn’t bother with any fancy addressing schemes. In Vert.x an address is simply a string. Any string is valid. However it is wise to use some kind of scheme, e.g. using periods to demarcate a namespace.

Some examples of valid addresses are "europe.news.feed1," "acme.games.pacman," "sausages," and "X."

=== Handlers
Messages are received in handlers. You register a handler at an address.  Many different handlers can be registered at the same address, and a single handler can be registered at many different addresses.

=== Publish / subscribe messaging
The event bus supports publishing messages.  Messages are published to an address. Publishing means delivering the message to all handlers that are registered at that address.

This is the familiar publish/subscribe messaging pattern.

=== Point to point and Request-Response messaging
The event bus also supports point to point messaging.

Messages are sent to an address. Vert.x will then route it to just one of the handlers registered at that address.  If there is more than one handler registered at the address, one will be chosen using a non-strict round-robin algorithm.

With point to point messaging, an optional reply handler can be specified when sending the message.

When a message is received by a recipient, and has been handled, the recipient can optionally decide to reply to the message. If they do so the reply handler will be called.

When the reply is received back at the sender, it too can be replied to. This can be repeated ad-infinitum, and allows a dialog to be set-up between two different verticles.

This is a common messaging pattern called the request-response pattern.

=== Best-effort delivery
Vert.x does it’s best to deliver messages and won’t consciously throw them away. This is called best-effort delivery.  However, in case of failure of all or parts of the event bus, there is a possibility messages will be lost.

If your application cares about lost messages, you should code your handlers to be idempotent, and your senders to retry after recovery.

=== Types of messages
Out of the box Vert.x allows any primitive/simple type, String, or buffers to be sent as messages.  However it’s a convention and common practice in Vert.x to send messages as JSON.  JSON is very easy to create, read and parse in all the languages that Vert.x supports so it has become a kind of lingua franca for Vert.x.

However you are not forced to use JSON if you don’t want to.

== Fail a Test!

Create a new test, PersistenceVerticleTest:

[code,java]
....

package io.vertx.conduit;

import io.vertx.conduit.model.User;
import io.vertx.core.Vertx;
import io.vertx.core.json.Json;
import io.vertx.core.json.JsonObject;
import io.vertx.junit5.Checkpoint;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import io.vertx.conduit.PersistenceVerticle;

import static io.vertx.conduit.PersistenceVerticle.*;
import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Persistence Event Bus Tests")
@ExtendWith(VertxExtension.class)
public class PersistenceVerticleTest {

  @Test
  @DisplayName("Register User Test") 
  @Timeout(2000)          <1>
  void testServerRegisterUserOverEventBus(Vertx vertx, VertxTestContext testContext) {

    Checkpoint deploymentCheckpoint = testContext.checkpoint();          <2>
    Checkpoint replyCheckpoint = testContext.checkpoint();          <3>

    User user = new User("user1@user.com", null, "user1", "user1's bio", null);          <4>

    JsonObject message = new JsonObject()
      .put(PERSISTENCE_ACTION, PERSISTENCE_ACTION_REGISTER)          <5>
      .put("user", Json.encode(user));

    vertx.deployVerticle(new PersistenceVerticle(), testContext.succeeding(id -> {          <5>
      deploymentCheckpoint.flag();          <6>
      vertx.eventBus().send(PERSISTENCE_ADDRESS, message, testContext.succeeding(ar -> {          <7>
        testContext.verify(() -> {          <8>
          assertEquals(PERSISTENCE_OUTCOME_SUCCESS, ((JsonObject) ar.body()).getString("outcome"));
          replyCheckpoint.flag();          <9>
          testContext.completeNow();          <10>
        });
      }));
    }));
  }

}

....
<1>  We haven't used the @Timeout annotation yet.  It is a useful addition for reasons that are probably obvious.  In this case we are testing multiple asynchronous actions so a Timeout while working on the test method can save time
<2>  We create 2 Checkpoint objects.  This one verifies our PersistenceVerticle is deployed successfully
<3>  This Checkpoint will be used to verify that our reply is received
<4>  Create a new to persist
<5>  There are 2 things to note about this line.  First, Json is the message format we are using on the event bus.  Second, our message includes instructions on how to handle the payload.  We are using String contstants to prevent fat finger errors.  We will add these constants into the EventBus Verticle in the next step.
<6>  Verify deployment
<7>  Send the message over the EventBus with the testContext.succeeding Handler.  The testContext.succeeding Hanlder automatically checks for the success of the result, and ends the test on failure
<8>  Now we actually verify the result
<9>  Flag the reply
<10> End the test

== Pass the Persistence Test (for a moment anyway)

[code,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonObject;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";


  @Override
  public void start(Future<Void> startFuture) throws Exception {

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });


  }

  private void registerUser(Message<JsonObject> message) {
    message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_FAILURE));
  }
}

....

=== And Pass the Endpoint Test

Add the call to the EventBus to the RegistrationEndpointTest (and spin up the PersistenceVerticle):

src/main/test/io/vertx/conduit/RegistrationEndpointTest.java
[code,java]
....

package io.vertx.conduit;

import io.vertx.conduit.model.User;
import io.vertx.conduit.persistence.PersistenceVerticle;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.web.client.WebClient;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static io.vertx.conduit.TestProps.*;
import static io.vertx.conduit.persistence.DatabaseProps.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

@DisplayName("Registration Endpoint Tests")
@ExtendWith(VertxExtension.class)
public class RegistrationEndpointTest {

  private JDBCClient jdbcClient;

  @BeforeEach          <1>
  void setUp(Vertx vertx, VertxTestContext testContext) {

    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {
      testContext.completeNow();
    }));
    vertx.deployVerticle(new PersistenceVerticle(), testContext.succeeding(ar ->  {          <2>
      testContext.completeNow();
    }));
  }

  @AfterEach
  void tearDown(Vertx vertx, VertxTestContext testContext) {          <3>
    vertx.close();
    testContext.completeNow();
  }


  @Test @Timeout(5000)
  public void testRegisteringNewUser(Vertx vertx, VertxTestContext testContext){

      WebClient webClient = WebClient.create(vertx);

      webClient.post(8080, "localhost", "/api/users")
        .sendJsonObject(new JsonObject()
          .put("user", new JsonObject()
            .put("username", "User2")
            .put("email", "user2@user2.user2")
            .put("password", "user2user2")
          ), testContext.succeeding(response ->  testContext.verify(()->{
            assertEquals(201, response.statusCode());
            testContext.completeNow();
          })));

  }

}

....

<1>  Move the initialization and clean up code into @BeforeEach and @AfterEach methods
<2>  Deploy the PersistenceVerticle 
<3>  Clean up

== Conclusion

Our test isn't really passing.  Let's be honest and change the reply's status to the constant PERSISTENCE_OUTCOME_FAILURE.

[code,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonObject;

public class PersistenceVerticle extends AbstractVerticle {

  public static final String PERSISTENCE_ADDRESS = "persistence-address";
  public static final String PERSISTENCE_ACTION = "action";
  public static final String PERSISTENCE_ACTION_REGISTER = "register";
  public static final String PERSISTENCE_OUTCOME = "outcome";
  public static final String PERSISTENCE_OUTCOME_SUCCESS = "success";
  public static final String PERSISTENCE_OUTCOME_FAILURE = "failure";


  @Override
  public void start(Future<Void> startFuture) throws Exception {

    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {
    message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_FAILURE));        <1>
  }
}

....

<1>  We will pass the test for real in the next step

Next up: accesing the database