= Step04: Authenticatng User Logins
:source-highlighter: prettify
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Summary

The second endpoint that we implement will be the Authentication endpoint (see next section.)  There are 2 reasons for this:

* Many of the endpoints require authentication so we might as well knock it out sooner rather than later
* The 3 tutorials at Thinkster.io all start with the Authentication endpoint, and we are doing our best to follow along as much as possible

Our first step will be to create a test (of course) and stub out the respone.
Our second step will be to add a databse 
step will be to create a test that attempts to authenticate using the example user, "jake@jake.jake"
We will then build the code to pass the test
* create a REST endpoint that accepts JSON in the expected format
* stub out the authentication and simply check hard coded values
* return the expected JSON User representation

== KeyTerms in this Step

Vert.x Authentication
AuthProvider
JDBCAuth

=== Vert.x Authentication

https://vertx.io/docs/vertx-auth-common/java/

The Vert.x Authorization component provides interfaces for authentication and authorisation that can be backed by different providers.  In Conduit we will use both the JDBCAuth for logging users in and the JWTAuth for accessing URLs

Since we are implementing the Login Endpoint in this Step we will use JDBCAuth

=== Vert.x JDBC Authentication

https://vertx.io/docs/vertx-auth-jdbc/java/

The dependency for Vert.x JDBCAuth can be found on line 55 of your pom.xml

/pom.xml
[code,xml]
....

<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-auth-jdbc</artifactId>
</dependency>

....

The JDBC AuthProvider expects things a certain way, and we will have to work around a couple of expectations while implementing the Conduit API

First, Conduit uses "email" and "password" for authentication (see below), and Vert.x JDBC AuthProvider expects "username" and "password" (see below below)

https://github.com/gothinkster/realworld/blob/master/api/README.md
[code,json]
....

{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

....

We will overcome this by simply specifying the query for JDBC AuthProvider to use

The second workaround will be in the JsonObject we pass to the JDBC AuthProvider.  The provider queries the JsonObject for the "username" property so we will simply provide the User's email as a value

Don't worry if this sounds confusing; it will be clear in a moment

== Fail a Test

Open PersistenceVerticle test and add another method, 

src/main/test/io/vertx/conduit/persistence/PersistenceVerticleTest
[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.conduit.model.User;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.json.Json;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.SQLConnection;
import io.vertx.junit5.Checkpoint;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static io.vertx.conduit.ApplicationProps.*;
import static io.vertx.conduit.TestProps.*;
import static io.vertx.conduit.persistence.DatabaseProps.*;
import static io.vertx.conduit.persistence.SQLQueries.SQL_SELECT_USER_BY_EMAIL;

@DisplayName("Persistence Event Bus Tests")
@ExtendWith(VertxExtension.class)
public class PersistenceVerticleTest {

  private JDBCClient jdbcClient;


  @BeforeEach
  void setUp(Vertx vertx, VertxTestContext testContext) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST));

    Flyway flyway = Flyway.configure().dataSource(DB_URL_TEST, DB_USER_TEST, null).load();
    // Run the migration
    flyway.migrate();

    Checkpoint deploymentCheckpoint = testContext.checkpoint();

    JsonObject eventBusDeploymentConfig = new JsonObject()
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST);

    vertx.deployVerticle(new PersistenceVerticle(), new DeploymentOptions().setConfig(eventBusDeploymentConfig),testContext.succeeding(id -> {
        deploymentCheckpoint.flag();
        Assertions.assertFalse(id.isEmpty());
    }));

    testContext.completeNow();
  }

  @Test
  @DisplayName("Authenticate User Test")
  @Timeout(10000)
  void testJDBCAuthorizationOverEventBus(Vertx vertx, VertxTestContext testContext) {          <1>
    Checkpoint replyCheckpoint = testContext.checkpoint();

    JsonObject message = new JsonObject()          <2>
      .put(PERSISTENCE_ACTION, PERSISTENCE_ACTION_LOGIN)
      .put("user", Json.encode(new User("jake@jake.jake", "password")));          <3>

    vertx.eventBus().send(PERSISTENCE_ADDRESS, message, testContext.succeeding(ar -> {          <4>
      testContext.verify(() -> {
        System.out.println(ar.body());
        Assertions.assertEquals(
          PERSISTENCE_OUTCOME_SUCCESS, 
          ((JsonObject) ar.body()).getString("outcome"));
        replyCheckpoint.flag();
        testContext.completeNow();
      });

    }));
  }

  @Test
  @DisplayName("Register User Test")
  @Timeout(10000)
  void testServerRegisterUserOverEventBus(Vertx vertx, VertxTestContext testContext) {

    Checkpoint replyCheckpoint = testContext.checkpoint();

    User user = new User("user1@user.com", null, "user1", "user1's bio", null, "password");

    JsonObject message = new JsonObject()
      .put(PERSISTENCE_ACTION, PERSISTENCE_ACTION_REGISTER)
      .put("user", Json.encode(user));

    JsonObject eventBusDeploymentConfig = new JsonObject()
      .put(DB_URL_KEY, DB_URL_TEST)
      .put(DB_DRIVER_KEY, DB_DRIVER_TEST)
      .put(DB_USER_KEY, DB_USER_TEST)
      .put(DB_POOL_SIZE_KEY, DB_POOL_SIZE_TEST);


      vertx.eventBus().send(PERSISTENCE_ADDRESS, message, testContext.succeeding(ar -> {
        testContext.verify(() -> {
          System.out.println(ar.body());

          // query database to verify insert
          jdbcClient.getConnection(conn ->{
            if (conn.failed()) {
              Assertions.assertTrue(conn.succeeded());
              testContext.completeNow();
            }
            final SQLConnection connection = conn.result();

            connection.queryWithParams(SQL_SELECT_USER_BY_EMAIL, new JsonArray().add(user.getEmail()), rs -> {
              if (rs.failed()) {
                Assertions.assertTrue(rs.succeeded());
                testContext.completeNow();
              }
              Assertions.assertEquals(1, rs.result().getNumRows());
              System.out.println(rs.result().getResults().get(0).encode());
            });
          });

          Assertions.assertEquals(PERSISTENCE_OUTCOME_SUCCESS, ((JsonObject) ar.body()).getString("outcome"));
          replyCheckpoint.flag();
          testContext.completeNow();
        });
      }));
  }

}

....

<1>  The new method
<2>  Create a JsonObject for the message payload
<3>  Create the login User inline
<4>  Send the message to the EventBus

Run the test

[code,shell]
....

mvn clean test -Dtest=PersistenceVerticleTest#testJDBCAuthorizationOverEventBus          <1>

....

<1>  Individual UnitTests (classes) as well as individual Tests (methods) can be specified using the above syntax

The test should fail, of course:

[code,shell]
....

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   PersistenceVerticleTest.testJDBCAuthorizationOverEventBus » Reply Unkown actio...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

....

== Pass the test

=== Update PersistenceVerticle

Open PersistenceVerticle and add a JDBCAuth provider:

src/main/java/io/vertx/conduit/persistence/PersistenceVerticle.java
[code,java]
....

package io.vertx.conduit.persistence;

import io.vertx.conduit.model.User;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.eventbus.Message;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.auth.jdbc.JDBCAuth;          <1>
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.UpdateResult;

import static io.vertx.conduit.ApplicationProps.*;
import static io.vertx.conduit.persistence.SQLQueries.SQL_LOGIN_QUERY;
import static io.vertx.conduit.persistence.SQLQueries.SQL_REGISTER_USER;
import static io.vertx.conduit.persistence.DatabaseProps.*;

public class PersistenceVerticle extends AbstractVerticle {

  private JDBCClient jdbcClient;

  private JDBCAuth authProvider;          <2>

  @Override
  public void start(Future<Void> startFuture) throws Exception {

    System.out.println(config().getString(DB_URL_KEY));

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put(DB_URL_KEY, config().getString(DB_URL_KEY, DB_URL_DEFAULT))
      .put(DB_DRIVER_KEY, config().getString(DB_DRIVER_KEY, DB_DRIVER_DEFAULT))
      .put(DB_USER_KEY, config().getString(DB_USER_KEY, DB_USER_DEFAULT))
      .put(DB_POOL_SIZE_KEY, config().getInteger(DB_POOL_SIZE_KEY, DB_POOL_SIZE_DEFAULT)));

    authProvider = JDBCAuth.create(vertx, jdbcClient);          <3>
    authProvider.setAuthenticationQuery(SQL_LOGIN_QUERY);          <4>


    EventBus eventBus = vertx.eventBus();
    MessageConsumer<JsonObject> consumer = eventBus.consumer(PERSISTENCE_ADDRESS);
    consumer.handler(message -> {

      String action = message.body().getString(PERSISTENCE_ACTION);

      switch (action) {
        case PERSISTENCE_ACTION_REGISTER:
          registerUser(message);
          break;
        default:
          message.fail(1, "Unkown action: " + message.body());
      }
    });

    startFuture.complete();

  }

  private void registerUser(Message<JsonObject> message) {

    JsonObject userJson = new JsonObject(message.body().getString("user"));
    User user = new User(userJson);

    jdbcClient.updateWithParams(SQL_REGISTER_USER, new JsonArray()
      .add(user.getUsername())
      .add(user.getEmail())
      .add(user.getBio())
      .add(user.getPassword())
      , res -> {
      if (res.succeeded()) {
        UpdateResult updateResult = res.result();
        System.out.println("No. of rows updated: " + updateResult.getUpdated());
        if (updateResult.getUpdated() >= 1) {
          message.reply(new JsonObject().put(PERSISTENCE_OUTCOME, PERSISTENCE_OUTCOME_SUCCESS));
        }else{
          message.fail(PersistenceErrorCodes.DB_INSERT_FAILURE.ordinal(), PersistenceErrorCodes.DB_INSERT_FAILURE  + res.cause().getMessage());
        }
      } else {
        message.fail(PersistenceErrorCodes.DB_CONNECTION_ERROR.ordinal(), PersistenceErrorCodes.DB_CONNECTION_ERROR + res.cause().getMessage());
      }

    });
  }
}

....

<1>  Be sure to import "io.vertx.ext.auth.jdbc.JDBCAuth"
<2>  Declare a member variable for the JDBCAuth authprovider
<3>  Initialize the authprovider with the local Vertx instance and JDBCClient
<4>  Specify the query to be used

NOTE: Vert.x Auth queries on "username" by default so we are overriding the query

=== Create a New Migration

There's no need to run the test yet.  Vert.x JDBCAuth is going to query 2 database fields, and only one of them is in our database

The default JDBC AuthProvider implementation assumes that the password is stored in the database as a SHA-512 hash after being concatenated with a salt. It also assumes the salt is stored in the table too

==== Create the User Table

Open V1_\_create-user-table.sql and update it with the following additional column:

src/main/java/resources/db/migration/V1_\_create-user-table.sql
[code,sql]
....

create table if not exists USER ("id" INT IDENTITY PRIMARY KEY ,
  "username" VARCHAR(255) NOT NULL ,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "bio" VARCHAR(255) ,
  "image" VARCHAR(255) ,
  "password" VARCHAR(255) NOT NULL,
  "password_salt" VARCHAR(255) NOT NULL);          <1>

....

<1>  This will store the password salt along with the hashed password

NOTE: Clever readers may be wondering when the password gets hashed because our registration code doesn't do that (yet.)  We will update the Register User functionality shortly

==== Insert a User for Authentication

We are also going to need some seed data in order to run our test.  Create a new migration, V1.1_\_insert-jacob.sql with the following insert statement:

[code,sql]
....

insert into USER (
    "username",
    "email",
    "bio",
    "image",
    "password",
    "password_salt"
    ) values (
    'jake',
    'jake@jake.jake',
    'I work at state farm',
    NULL,
    '39DF2CF3B01EA60EF66DE648CE6CE0B5AD3F99DC2E1816F79186741E9A0444C58B17580D8F9D48C0FB033606A8C515DA7C5B6C792B710ECCB9FEF1429D51E3CE',          <1>
    'BFB49A9B9CDDDF7C488CB2D84E8DDED8EEC01FFDD26B487DC08E5A4CAB6E4D10');          <2>

....

<1>  You will have to trust me on the hashed password for the moment
<2>  Same



//================================================================
=== A Bit About the Authentication Endpoint

The endpoint we will implement in this step the Authentication endpoint, documented here:
https://github.com/gothinkster/realworld/blob/master/api/README.md

POST /api/users/login

Input:
[code,json]
....
{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}
....

Expected Return:
[code,json]
....
{
  "user": {
    "email": "jake@jake.jake",
    "token": "jwt.token.here",
    "username": "jake",
    "bio": "I work at statefarm",
    "image": null
  }
}

....

== Test JDBC Authentication First!

Open PersistenceVerticleTest


== Test our Endpoint First!

Create a new class, AuthenticationEndpointTests

src/test/java/io/vertx/conduit/AuthenticationEndpointTests
[source,java]
....

package io.vertx.conduit;

import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.client.WebClient;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DisplayName("Authentication Endpoint Tests")
@ExtendWith(VertxExtension.class)
public class AuthenticationEndpointTest {

  @Test
  public void testAuthentication(Vertx vertx, VertxTestContext testContext){
    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {
      WebClient webClient = WebClient.create(vertx);
      webClient.post(8080, "localhost", "/api/users/login")
        .sendJsonObject(new JsonObject()
        .put("user", new JsonObject()
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
        ), response -> testContext.verify(() -> {
        assertEquals(200, response.result().statusCode());
        JsonObject user = response.result().bodyAsJsonObject().getJsonObject("user");
        System.out.println(user.encodePrettily());
        assertEquals("jake@jake.jake", user.getString("email"));
        assertEquals("jakejake", user.getString("password"));
        assertNotNull( user.getString("token"));
        assertEquals("jake", user.getString("username"));
        assertEquals("I work at statefarm", user.getString("bio"));
        assertEquals("", user.getString("image"));
        testContext.completeNow();
      }));
    }));
  }
}

....

=== Implement the Test Method

[source,java]
....
    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {              <1>             
      WebClient webClient = WebClient.create(vertx);                                     <2>
      webClient.post(8080, "localhost", "/api/users/login")                              <3>
        .sendJsonObject(new JsonObject()                                                 <4>
          .put("user", new JsonObject()
            .put("email", "jake@jake.jake")
            .put("password", "jakejake")
          ), response -> testContext.verify(() -> {                                      <5>
          JsonObject user = response.result().bodyAsJsonObject().getJsonObject("user");  <6>
          assertEquals(200, response.result().statusCode());                             <7>
          assertEquals("jake@jake.jake", user.getString("email"));                       <8>
          assertEquals("jakejake", user.getString("password"));
          assertEquals("jwt.token.here", user.getString("token"));
          assertEquals("jake", user.getString("username"));
          assertEquals("I work at statefarm", user.getString("bio"));
          assertEquals("", user.getString("image"));
          testContext.completeNow();                                                     <9>
        }));
    }));
....

<1> Deploy our MainVerticle
<2> Create a WebClient to call the endpoint
<3> Use the WebClient to post Json to the URI
<4> We can create a new JsonObject as an inline argument to the .sendJsonObject method
<5> This lambda performs the actual work of the test
<6> Unmarshall the response
<7> Verify the status code of our response
<8> The next lines verify the resulting Json
<9> Finish the test by calling completeNow()

== Stub out the Response

[source,java]
....
  private void loginHandler(RoutingContext context) {
    JsonObject user = context.getBodyAsJson().getJsonObject("user");     <1>
    if(
      user.getString("email").equalsIgnoreCase("jake@jake.jake") &&
      user.getString("password").equalsIgnoreCase("jakejake")){         <2>

      JsonObject returnValue = new JsonObject()     <3>
        .put("user", new JsonObject()
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
          .put("token", "jwt.token.here")
          .put("username", "jake")
          .put("bio", "I work at statefarm")
          .put("image", ""));
      System.out.println(returnValue);

      HttpServerResponse response = context.response();
      response.setStatusCode(200)     <4>
        .putHeader("Content-Type", "application/json; charset=utf-8")     <5>
        .putHeader("Content-Length", String.valueOf(returnValue.toString().length()))     <6>
        .end(returnValue.toString());     <7>

    }else{
      context.response()
        .setStatusCode(401)
        .putHeader("Content-Type", "text/html")
        .end("Go away");
    }
  }
....
<1> Unmarshall the Json from the request into a JsonObject
<2> Check the values for "user" and "password"
<3> Create the Json for our response
<4>
<5>
<6>
<7>

== Lookuping the User

We have the endpoint, but it isn't doing anything at the moment.  In order to actually authenticate users we will need to look them up from a database.  To do that we will need to:
* create a database
* prepopulate the database with data
* connect and lookup our user, "jake@jake.jake"

=== Adding a Database

==== HyperSQL
HyperSQL, http://hsqldb.org, is a small relational database that can be accessed in-memory data store and on the file system.  It isn't recommended for production systems, but it is an excellent choice for development.

The database dependencies can be found in the pom.xml

[source,xml]
....
    <!-- Database Dependencies -->
    <dependency>
      <groupId>io.vertx</groupId> 
      <artifactId>vertx-jdbc-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
    </dependency>
....

The first step is to add a Vert.x JDBCClient to the MainVerticle as a class variable:

[source,java]
....
  import io.vertx.ext.jdbc.JDBCClient;
  ...
public class MainVerticle extends AbstractVerticle {

  private JDBCClient jdbcClient;                                   <1>

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()   <2>
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    Router baseRouter = Router.router(vertx);
    ...
....
<1> Create a member variable
<2> Instantiate the JDBClient py passing in our vertx Object and configuration in the form of a JsonObject

==== AuthProvider

Add a JDBCAuth provider and instantiate it by passing in 

[source,java]
....
import io.vertx.ext.auth.jdbc.JDBCAuth;

public class MainVerticle extends AbstractVerticle {

  private JDBCAuth authProvider;

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    authProvider = JDBCAuth.create(vertx, jdbcClient);
....

Instantiate it 
==== JsonObject

[source,java]
....
    JsonObject userLogin = new JsonObject()
      .put("user", new JsonObject()
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
      );

    JsonObject expectedReturn = new JsonObject()
      .put("user", new JsonObject()
        .put("email", "jake@jake.jake")
        .put("password", "jakejake")
        .put("token", "jwt.token.here")
        .put("username", "jake")
        .put("bio", "I work at statefarm")
        .put("image", ""));
....

==== Test Method
[source,java]
....
    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {
      deploymentCheckpoint.flag();

      webClient.post(8080, "localhost", "/")
        .as(BodyCodec.string())
        .sendJsonObject(userLogin, resp -> {
          authenticationCheckpoint.flag();
          assertEquals(200, resp.result().statusCode());
          assertEquals(expectedReturn, resp.result().bodyAsJsonObject());
        });
    }));
....

=== Run the Test

[source,shell]
....
mvn clean test
...
[ERROR] Failures:
[ERROR]   AuthenticationEndpointTest.testSuccessfulAuthentication org.opentest4j.AssertionFailedError: expected: <{"user":{"email":"jake@jake.jake","password":"jakejake","token":"jwt.token.here","username":"jake","bio":"I work at statefarm","image":""}}> but was: <null>
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
....

== Add the Route and Handler

[source,java]
....
    router.route("/api/users/login").handler(this::loginHandler);
....

== Create our Users domain model

[source,java]
....
package io.vertx.thinkster.conduit.domain;

public class User {

  private String email;

  private String token;

  private String username;

  private String bio;

  private String image;

  public User(String email, String token, String username, String bio, String image) {
    this.email = email;
    this.token = token;
    this.username = username;
    this.bio = bio;
    this.image = image;
  }

  @Override
  public String toString() {
    return "User{" +
      "email='" + email + '\'' +
      ", token='" + token + '\'' +
      ", username='" + username + '\'' +
      ", bio='" + bio + '\'' +
      ", image='" + image + '\'' +
      '}';
  }

  public User(String email) {
    this.email = email;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }
}

....

== /api/users/login

Steps

* Create the Users object of our domain model
* Add a new route
* Attach a handler to the route
* Implement the handler
* Validate the required fields
* Extract the posted data
* Lookup the user (we will stub this out for now)
* Return the expected result


Add a new route: 

[code,java]
....
    router.route("/api/users/login").handler(this::loginHandler);
....

Implement loginHandler

[code,java]
....
    User user = new User();
    user.setUsername("vertx-user");
    user.setBio("Mock bio");
    user.setEmail("user@vertx.io");
    user.setToken("token");

    HttpServerResponse response = routingContext.response();
    response
      .putHeader("content-type", "text/html")
      .end(Json.encodePrettily(user));
....

./redeploy.sh

== Postman and Newman
update the variables with "localhost:8080/api"
pass the first Postman test Auth/login

== Handle the actual request values

Create a domain model to handle errors:

[code,java]
....
package io.vertx.thinkster.conduit.domain;

public class ConduitError {

  private Error error;

  public ConduitError() {

    this.error = new Error("Something went wrong");

  }

  public ConduitError(String body) {

    this.error = new Error(body);
  }

  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }

  private class Error {

    private String body;

    public Error(String body) {
      this.body = body;
    }

    public String getBody() {
      return body;
    }

    public void setBody(String body) {
      this.body = body;
    }

  }

}
....

