= Step 03 : Implement Our First Endpoint
:source-highlighter: prettify
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== KeyTerms in this Step

BodyHandler
JsonObject
WebClient
Flyway

== Summary

The Conduit API can be found on Thinkster's Github : https://github.com/gothinkster/realworld/blob/master/api/README.md

The first endpoint that we will implement will be the Registration endpoint 

The Registration endpoint expects a Post request at "/api/users" with the following body:

[code,json]
....

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

....

Our API defines the following response:

[code,json]
....

{
  "user": {
    "email": "jake@jake.jake",
    "token": "jwt.token.here",
    "username": "jake",
    "bio": "I work at statefarm",
    "image": null
  }
}

....

Starting with Registration will make it easy to add new users because we can simply excercise our test cases with new values.  It will also introduce many of the core concepts that we will be using including:

Vertx WebClient for making HTTP calls
Vertx JDBC for database access
Flyway for databse migrations

The 3 tutorials at Thinkster.io all start with the Authentication endpoint.  We will get to that one in the next section.

== Test First!

Red, Green, Refactor...

Our first step will be to create a test (of course) and stub out the respone

We will then build the code to pass the test

* create our database using Flyway
* create a REST endpoint that accepts JSON in the expected format
* marshall the JSON into a domain object
* persist the User posted to our endpoint
* return the expected JSON User representation

Create a new class, RegistrationEndpointTest, in the io.vertx.conduit package

[source,java]
....

package io.vertx.conduit;

import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.client.WebClient;          <1>
import io.vertx.junit5.VertxExtension;          <2>
import io.vertx.junit5.VertxTestContext;          <3>
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.junit.jupiter.api.Assertions.assertEquals;          <4>

@DisplayName("Authentication Endpoint Tests")
@ExtendWith(VertxExtension.class)          <5>
public class RegistrationEndpointTest {

  @Test
  public void testRegisteringNewUser(Vertx vertx, VertxTestContext testContext){
    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {
      WebClient webClient = WebClient.create(vertx);          <6>
      webClient.post(8080, "localhost", "/api/users")          <7>
        .sendJsonObject(new JsonObject()          <8>
          .put("user", new JsonObject()
            .put("username", "Jacob")
            .put("email", "jake@jake.jake")
            .put("password", "jakejake")
          ), response -> testContext.verify(() -> {
          assertEquals(200, response.result().statusCode());          <9>
          JsonObject user = response.result().bodyAsJsonObject().getJsonObject("user");          <10>
          assertEquals("jake@jake.jake", user.getString("email"));          <11>
          assertEquals("jakejake", user.getString("password"));
          assertEquals("Jacob", user.getString("username"));
          testContext.completeNow();          <12>
        }));
    }));
  }

}

....


<1>  Your or your IDE needs to import "io.vertx.ext.web.client.WebClient"
<2>  Your or your IDE needs to import "import io.vertx.junit5.VertxExtension"
<3>  Your or your IDE needs to import "import io.vertx.junit5.VertxTestContext"
<4>  JUnit 5 is a major change from previous versions.  All assertions are now in the Jupiter API module
<5>  We extend JUnit's basic functionality with the VertxExtension
<6>  Create a WebClient to call our URI
<7>  Make a post call to "/api/users"
<8>  Define the Json we are sending in the POST request
<9>  Verify the Response' status code
<10> Get the Json from the Response and store it in a local variable, "user"
<11> Verify only the parameters that posted
<12> End the test.  It is important to make sure we wrap up our tests because you can easily find yourself wondering why your Unit Test is hanging or why your Unit Test ended so quickly

=== Run the Test

[code,shell]
....

mvn clean test

....

The test shouldn't pass at this point, but it is important to regularly run your test cases

[code,shell]
....

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 s - in io.vertx.conduit.MainVerticleTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   RegistrationEndpointTest.lambda$null$1:29->lambda$null$0:31 » Decode Failed to...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.657 s
[INFO] Finished at: 2018-10-11T14:59:22-04:00
[INFO] Final Memory: 22M/309M
[INFO] ------------------------------------------------------------------------

....

The test fails of course because we aren't serving anything at "/api/users" 

=== Pass the Test

==== Create a Domain Model for User

Create a domain model to represent the Conduit API's user, User in a new package, "io.vertx.conduit.model"

This object is mostly self-explanatory, but there are two things in particular that is unusual: the toJsonObject() method and the constructor that takes a JsonObject

[code,java]
....

package io.vertx.conduit.model;

import io.vertx.core.json.JsonObject;

public class User {

  String email;

  String token;

  String username;

  String bio;

  String image;

  /**
   * JsonObject in the format the Conduit API's expect
    *
   * @return JsonObject
   */
  public JsonObject toJsonObject() {          <1>

    return new JsonObject()
      .put("user", new JsonObject()
        .put("email", this.email)
        .put("token", this.token)
        .put("username", this.username)
        .put("bio", this.bio)
        .put("image", this.image));
  }

  /**
   * Constructor that takes a JsonObject representing the User
   *
   * @param jsonObject
   */
  public User(JsonObject jsonObject) {          <2>
    this.email = jsonObject.getString("email");
    this.token = jsonObject.getString("token");
    this.username = jsonObject.getString("username");
    this.bio = jsonObject.getString("bio");
    this.image = jsonObject.getString("image");
  }

  public User() {
  }

  public User(String email, String token, String username, String bio, String image) {
    this.email = email;
    this.token = token;
    this.username = username;
    this.bio = bio;
    this.image = image;
  }

  @Override
  public String toString() {
    return "User{" +
      "email='" + email + '\'' +
      ", token='" + token + '\'' +
      ", username='" + username + '\'' +
      ", bio='" + bio + '\'' +
      ", image='" + image + '\'' +
      '}';
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }
}

....

<1>  Vert.x can very smoothly encode Java POJO's, but to match the Conduit API we need to nest the User model in another JsonObject, "user"
<2>  Vert.x can natively encode and decode Json, but adding this method will make it even easier to marshall our User model to and from Json

==== Register the Endpoint

First things first we need to register, "/api/users" with our router.  We're going to do that by creating a new Router to handle all requests that begin with "/api"

[source,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.BodyHandler;

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Future<Void> startFuture) {

    Router baseRouter = Router.router(vertx);
    baseRouter.route("/").handler(this::indexHandler);

    Router apiRouter = Router.router(vertx);          <1>
    apiRouter.route("/*").handler(BodyHandler.create());          <2>
    apiRouter.post("/users/login").handler(this::registrationHandler);          <3>

    baseRouter.mountSubRouter("/api", apiRouter);          <4>

    vertx.createHttpServer()
        .requestHandler(req -> req.response().end("Hello, Conduit!"))
        .listen(8080);
    startFuture.complete();
  }

  private void indexHandler(RoutingContext routingContext) {
    HttpServerResponse response = routingContext.response();
    response
      .putHeader("Content-Type", "text/html")
      .end("Hello Conduit!");
  }

}

....

<1>  Create a new Router named, "apiRouter"
<2>  Create a BodyHandler for all of the endpoints.  Vert.x' BodyHandler enables us to manipulate request data
<3>  Register our endpoint, "/api/users"
<4>  Attach our apiRouter to the previously defined baseRouter

Your IDE is probably complaining at the moment because there isn't a "registrationHandler" method.  Let's fix that.

==== Attach a Handler to the Endpoint

We are going to quickly stub out a response to get a feel for what we are building.

[source,java]
....

package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.BodyHandler;

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Future<Void> startFuture) {

    Router baseRouter = Router.router(vertx);
    baseRouter.route("/").handler(this::indexHandler);

    Router apiRouter = Router.router(vertx);
    apiRouter.route("/*").handler(BodyHandler.create());
    apiRouter.post("/users").handler(this::registrationHandler);

    baseRouter.mountSubRouter("/api", apiRouter);

    vertx
      .createHttpServer()
      .requestHandler(baseRouter::accept)
      .listen(8080, result -> {
        if (result.succeeded()) {
          startFuture.complete();
        }else {
          startFuture.fail(result.cause());
        }
      });
  }

  private void registrationHandler(RoutingContext routingContext) {

    JsonObject user = routingContext.getBodyAsJson().getJsonObject("user");          <1>

    JsonObject returnValue = new JsonObject()          <2>
      .put("user", new JsonObject()
        .put("email", user.getString("email"))
        .put("password", user.getString("password"))
        .put("token", "")
        .put("username", user.getString("username"))
        .put("bio", "")
        .put("image", ""));
    routingContext.response()
      .setStatusCode(201)          <3>
      .putHeader("Content-Type", "application/json; charset=utf-8")          <4>
      .end(returnValue.encodePrettily());          <5>
  }

  private void indexHandler(RoutingContext routingContext) {
    HttpServerResponse response = routingContext.response();
    response
      .putHeader("Content-Type", "text/html")
      .end("Hello Conduit!");
  }

}

....

<1>  Unmarshall the Json from the request into a JsonObject
<2>  Create the Json for our response
<3>  Set the status code to "201" which is "Created"
<4>  Set the content type 
<6>  Return the Json

At this point our test will pass, but it isn't really doing anything.  We need to insert the user into the database.

== Adding a Database

==== HyperSQL (HSQLDB)

HyperSQL, http://hsqldb.org, is a small relational database that can be store data in-memory or on the file system.  We will use both methods in ths project.

HSQLDB isn't recommended for production systems, but it is an excellent choice for development.

The database dependencies can be found in the pom.xml

[source,xml]
....
    <!-- Database Dependencies -->
    <dependency>
      <groupId>io.vertx</groupId> 
      <artifactId>vertx-jdbc-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
    </dependency>
....

The first step is to add a Vert.x JDBCClient to the MainVerticle as a class variable:

[source,java]
....
  import io.vertx.ext.jdbc.JDBCClient;
  ...
public class MainVerticle extends AbstractVerticle {

  private JDBCClient jdbcClient;                                   <1>

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()   <2>
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    Router baseRouter = Router.router(vertx);
    ...
....
<1> Create a member variable
<2> Instantiate the JDBClient py passing in our vertx Object and configuration in the form of a JsonObject

== Looking Up the User

We have the endpoint, but it isn't doing anything at the moment.  In order to actually authenticate users we will need to look them up from a database.  To do that we will need to:
* create a database
* prepopulate the database with data
* connect and lookup our user, "jake@jake.jake"

=== Adding a Database

==== HyperSQL
HyperSQL, http://hsqldb.org, is a small relational database that can be accessed in-memory data store and on the file system.  It isn't recommended for production systems, but it is an excellent choice for development.

The database dependencies can be found in the pom.xml

[source,xml]
....
    <!-- Database Dependencies -->
    <dependency>
      <groupId>io.vertx</groupId> 
      <artifactId>vertx-jdbc-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
    </dependency>
....

The first step is to add a Vert.x JDBCClient to the MainVerticle as a class variable:

[source,java]
....
  import io.vertx.ext.jdbc.JDBCClient;
  ...
public class MainVerticle extends AbstractVerticle {

  private JDBCClient jdbcClient;                                   <1>

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()   <2>
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    Router baseRouter = Router.router(vertx);
    ...
....
<1> Create a member variable
<2> Instantiate the JDBClient py passing in our vertx Object and configuration in the form of a JsonObject

==== AuthProvider

Add a JDBCAuth provider and instantiate it by passing in 

[source,java]
....
import io.vertx.ext.auth.jdbc.JDBCAuth;

public class MainVerticle extends AbstractVerticle {

  private JDBCAuth authProvider;

  private JDBCClient jdbcClient;

  @Override
  public void start(Future<Void> future) {

    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
      .put("url", "jdbc:hsqldb:file:db/wiki")
      .put("driver_class", "org.hsqldb.jdbcDriver")
      .put("max_pool_size", 30));

    authProvider = JDBCAuth.create(vertx, jdbcClient);
....

Instantiate it 
==== JsonObject

[source,java]
....
    JsonObject userLogin = new JsonObject()
      .put("user", new JsonObject()
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
      );

    JsonObject expectedReturn = new JsonObject()
      .put("user", new JsonObject()
        .put("email", "jake@jake.jake")
        .put("password", "jakejake")
        .put("token", "jwt.token.here")
        .put("username", "jake")
        .put("bio", "I work at statefarm")
        .put("image", ""));
....

==== Test Method
[source,java]
....
    vertx.deployVerticle(new MainVerticle(), testContext.succeeding(id -> {
      deploymentCheckpoint.flag();

      webClient.post(8080, "localhost", "/")
        .as(BodyCodec.string())
        .sendJsonObject(userLogin, resp -> {
          authenticationCheckpoint.flag();
          assertEquals(200, resp.result().statusCode());
          assertEquals(expectedReturn, resp.result().bodyAsJsonObject());
        });
    }));
....

=== Run the Test

[source,shell]
....
mvn clean test
...
[ERROR] Failures:
[ERROR]   AuthenticationEndpointTest.testSuccessfulAuthentication org.opentest4j.AssertionFailedError: expected: <{"user":{"email":"jake@jake.jake","password":"jakejake","token":"jwt.token.here","username":"jake","bio":"I work at statefarm","image":""}}> but was: <null>
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
....

== Add the Route and Handler

[source,java]
....
    router.route("/api/users/login").handler(this::loginHandler);
....

== Create our Users domain model

[source,java]
....
package io.vertx.thinkster.conduit.domain;

public class User {

  private String email;

  private String token;

  private String username;

  private String bio;

  private String image;

  public User(String email, String token, String username, String bio, String image) {
    this.email = email;
    this.token = token;
    this.username = username;
    this.bio = bio;
    this.image = image;
  }

  @Override
  public String toString() {
    return "User{" +
      "email='" + email + '\'' +
      ", token='" + token + '\'' +
      ", username='" + username + '\'' +
      ", bio='" + bio + '\'' +
      ", image='" + image + '\'' +
      '}';
  }

  public User(String email) {
    this.email = email;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }
}

....

== /api/users/login

Steps

* Create the Users object of our domain model
* Add a new route
* Attach a handler to the route
* Implement the handler
* Validate the required fields
* Extract the posted data
* Lookup the user (we will stub this out for now)
* Return the expected result


Add a new route: 

[code,java]
....
    router.route("/api/users/login").handler(this::loginHandler);
....

Implement loginHandler

[code,java]
....
    User user = new User();
    user.setUsername("vertx-user");
    user.setBio("Mock bio");
    user.setEmail("user@vertx.io");
    user.setToken("token");

    HttpServerResponse response = routingContext.response();
    response
      .putHeader("content-type", "text/html")
      .end(Json.encodePrettily(user));
....

./redeploy.sh

== Postman and Newman
update the variables with "localhost:8080/api"
pass the first Postman test Auth/login

== Handle the actual request values

Create a domain model to handle errors:

[code,java]
....
package io.vertx.thinkster.conduit.domain;

public class ConduitError {

  private Error error;

  public ConduitError() {

    this.error = new Error("Something went wrong");

  }

  public ConduitError(String body) {

    this.error = new Error(body);
  }

  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }

  private class Error {

    private String body;

    public Error(String body) {
      this.body = body;
    }

    public String getBody() {
      return body;
    }

    public void setBody(String body) {
      this.body = body;
    }

  }

}
....

