= Step 02 : REST Basics with Vert.x-Web
:source-highlighter: coderay

== Vert.x-Web

https://vertx.io/docs/vertx-web/java/

We will be using Vert.x-Web to build our endpoints.  

Vert.x-Web is in the vertx-conduit-starter pom.xml on line 36:

[code,xml]
....
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web</artifactId>
</dependency>
....

Vert.x-Web is as a Swiss Army Knife for building modern, scalable, web apps.  Vert.x core provides a fairly low level set of functionality for handling HTTP, and for some applications that will be sufficient.  Vert.x-Web adds functionality for building real web applications and is especially awesome for building REST APIs and REST based microservices.

Vert.x-Web is influenced by Express in the NodeJS world and Sinatra in the Ruby world so if you have used either of those projects you will feel right at home. 

MainVerticle.java currently creates an HTTP server, listens on port 8080 and returns "Hello Vert.x!" using the Vert.x's core HTTP functionality.  Since we will be using the Vert.x-Web package our first step is to delete this basic implementation and begin building our APIs.

=== Vert.x-Web Router

Vert.x-Web contains a "Router" that maps URLs to Java methods.  Our first step is to add the Router to our start method.

[code,java,linenums]
....
    import io.vertx.ext.web.Router;

    Router router = Router.router(vertx);
    router.route("/").handler(this::indexHandler);
....

