= Step 1 : Getting Started
:source-highlighter: coderay

== Clone the Vert.x Starter Project
[source,shell]
----
git clone https://github.com/jeremyrdavis/vertx-conduit-starter.git (1)
cd vertx-conduit-starter (2)
rm -Rf .git (3)
git init (4)
----
* This is a basic Vert.x project that we will use as a starting point
* Change into the project directory
* Delete the existing Git repository
* Initialize a new Git repository to hold our changes

=== Create a Remote Repository (Optional, but Recommended)
Keeping a remote copy for yourself is useful while making changes
Create a repository in Github
[source,shell]
....
git remote add origin https://github.com/[YOUR GITHUB NAME]/thinkster-vertx.git
git push -u origin master
....

=== Update the pom
Using the text editor of your choice:
1. Open up pom.xml
2. Change the groupId to: io.vertx.conduit
3. Change the artifactId to : vertx-conduit
4. Change the main.verticle to: <main.verticle>io.vertx.conduit.MainVerticle</main.verticle>

The result should look like this:
[source,xml]
....
  <groupId>io.vertx.conduit</groupId>
  <artifactId>vertx-conduit-starter</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <vertx.version>3.5.2</vertx.version>
    <main.verticle>io.vertx.starter.MainVerticle</main.verticle>
  </properties>
....

=== IDE Time

==== IntelliJ

==== About
https://www.jetbrains.com/idea/

==== Creating a new project
1. Choose "File -> New -> Project From Existing Sources..."
2. Browse to the directory holding your project and choose the directory itself and choose "Open."  This will start an import wizard
3. "Maven" should already be selected in the "Import Project" dialog.  Click, "Next"
4. "Root Directory" should be highlighted with the directory of your project.  Click, "Next"
5. "redhat-jboss-ga" and "techpreview-all-repository" should already be selected.  Click, "Next"
6. "io.vertx.starter:vertx-thinkster:1.0-SNAPSHOT
7.  Be sure to select JDK 1.8.  Click, "Next"
8.  Project name should be "vertx-thinkster."  Click, "Finish"
9.  You can open the project in a new window or use your existing one

We will be using mvn directly for this tutorial.  You can run the following terminal commands in IntelliJ's Terminal window if you like.

==== Eclipse
==== Visual Studio Code

== Real Work!

=== Build and test 

For simplicity's sake we will use maven to build and test.  You are welcome to use your IDE's mechanism if you prefer, but we recommend checking every now again with Maven on the command line just to be sure your IDE hasn't added something magical in the background. 

[source,shell]
....
mvn clean package
....

You should successfully build and pass the default test.

Open up the "target" directory, and you will see 2 jar files.  We will be running our application from the "-fat.jar"

=== Launch our first Verticle

Let's fire up our first verticle!

NOTE: Verticles are the most basic unit of work in Vert.x


[source,shell]
....
mvn clean package
java -jar ./target/vertx-conduit-1.0-SNAPSHOT-fat.jar
....

Open http://localhost:8080.  You should see, "Hello, Vert.x!"

Ctrl + c to stop the server

=== redeploy.sh
Our default project contains 2 redeploy files, "redeploy.sh" and "redeploy.bat," that will keep your application running and redploy when you make changes.

Start your application with the redeploy scripts:
[source,shell]
....
./redeploy.sh or redeploy.bat
....

Open http://localhost:8080/
You should see the same text you saw when running the fat jar, "Hello, Vert.x!"

Open src/main/java/io/vertx/start/MainVerticle.java

Change the "Hello, Vert.x" text to "Hello, Conduit"
Check your browser again.  You should see, "Hello, Conduit"

Stop your application with Ctrl + c

